import { TopicContent } from '../../types'

export const NDA_GAT_POLITY_AUTOGEN: TopicContent[] = [
  {
    id: 'nda-polity-fr',
    title: 'Fundamental Rights (Articles 12-35)',
    readTimeMinutes: 18,
    content: [
      { type: 'heading', data: 'Fundamental Rights (Articles 12-35) Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Fundamental Rights (Articles 12-35). The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Fundamental Rights (Articles 12-35)',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Fundamental Rights (Articles 12-35)',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Fundamental Rights (Articles 12-35)?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-polity-freedom',
    title: 'Indian Freedom Movement (1857-1947)',
    readTimeMinutes: 16,
    content: [
      { type: 'heading', data: 'Indian Freedom Movement (1857-1947) Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Freedom Movement (1857-1947). The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Freedom Movement (1857-1947)',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Freedom Movement (1857-1947)',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Freedom Movement (1857-1947)?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-ai-01',
    title: 'Preamble and Salient Features of Indian Constitution',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Preamble and Salient Features of Indian Constitution Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Preamble and Salient Features of Indian Constitution. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Preamble and Salient Features of Indian Constitution',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Preamble and Salient Features of Indian Constitution',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Preamble and Salient Features of Indian Constitution?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-ai-02',
    title: 'Fundamental Rights and Duties (Article 12-35)',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Fundamental Rights and Duties (Article 12-35) Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Fundamental Rights and Duties (Article 12-35). The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Fundamental Rights and Duties (Article 12-35)',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Fundamental Rights and Duties (Article 12-35)',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Fundamental Rights and Duties (Article 12-35)?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-ai-03',
    title: 'Directive Principles of State Policy',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Directive Principles of State Policy Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Directive Principles of State Policy. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Directive Principles of State Policy',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Directive Principles of State Policy',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Directive Principles of State Policy?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-ai-04',
    title: 'President, Prime Minister and Council of Ministers',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'President, Prime Minister and Council of Ministers Overview' },
      { type: 'text', data: 'This is the autogenerated study material for President, Prime Minister and Council of Ministers. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of President, Prime Minister and Council of Ministers',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of President, Prime Minister and Council of Ministers',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying President, Prime Minister and Council of Ministers?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-ai-05',
    title: 'Parliament - Lok Sabha and Rajya Sabha',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Parliament - Lok Sabha and Rajya Sabha Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Parliament - Lok Sabha and Rajya Sabha. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Parliament - Lok Sabha and Rajya Sabha',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Parliament - Lok Sabha and Rajya Sabha',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Parliament - Lok Sabha and Rajya Sabha?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-ai-06',
    title: 'Judiciary - Supreme Court and High Courts',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Judiciary - Supreme Court and High Courts Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Judiciary - Supreme Court and High Courts. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Judiciary - Supreme Court and High Courts',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Judiciary - Supreme Court and High Courts',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Judiciary - Supreme Court and High Courts?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-ai-07',
    title: 'Constitutional Amendments and Emergency Provisions',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Constitutional Amendments and Emergency Provisions Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Constitutional Amendments and Emergency Provisions. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Constitutional Amendments and Emergency Provisions',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Constitutional Amendments and Emergency Provisions',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Constitutional Amendments and Emergency Provisions?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-51',
    title: 'Indian Polity & Constitution - Advanced Topic 51',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 51 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 51. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 51',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 51',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 51?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-54',
    title: 'Indian Polity & Constitution - Advanced Topic 54',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 54 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 54. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 54',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 54',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 54?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-57',
    title: 'Indian Polity & Constitution - Advanced Topic 57',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 57 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 57. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 57',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 57',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 57?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-60',
    title: 'Indian Polity & Constitution - Advanced Topic 60',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 60 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 60. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 60',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 60',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 60?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-63',
    title: 'Indian Polity & Constitution - Advanced Topic 63',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 63 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 63. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 63',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 63',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 63?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-66',
    title: 'Indian Polity & Constitution - Advanced Topic 66',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 66 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 66. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 66',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 66',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 66?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-69',
    title: 'Indian Polity & Constitution - Advanced Topic 69',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 69 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 69. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 69',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 69',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 69?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-72',
    title: 'Indian Polity & Constitution - Advanced Topic 72',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 72 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 72. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 72',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 72',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 72?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-75',
    title: 'Indian Polity & Constitution - Advanced Topic 75',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 75 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 75. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 75',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 75',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 75?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-78',
    title: 'Indian Polity & Constitution - Advanced Topic 78',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 78 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 78. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 78',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 78',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 78?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-81',
    title: 'Indian Polity & Constitution - Advanced Topic 81',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 81 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 81. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 81',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 81',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 81?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-84',
    title: 'Indian Polity & Constitution - Advanced Topic 84',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 84 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 84. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 84',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 84',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 84?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-87',
    title: 'Indian Polity & Constitution - Advanced Topic 87',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 87 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 87. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 87',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 87',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 87?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-90',
    title: 'Indian Polity & Constitution - Advanced Topic 90',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 90 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 90. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 90',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 90',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 90?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-93',
    title: 'Indian Polity & Constitution - Advanced Topic 93',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 93 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 93. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 93',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 93',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 93?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-96',
    title: 'Indian Polity & Constitution - Advanced Topic 96',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 96 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 96. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 96',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 96',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 96?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-polity-bulk-99',
    title: 'Indian Polity & Constitution - Advanced Topic 99',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Indian Polity & Constitution - Advanced Topic 99 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian Polity & Constitution - Advanced Topic 99. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian Polity & Constitution - Advanced Topic 99',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian Polity & Constitution - Advanced Topic 99',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian Polity & Constitution - Advanced Topic 99?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
]
