import { TopicContent } from '../../types'

export const NDA_ALGEBRA_AUTOGEN: TopicContent[] = [
  {
    id: 'nda-alg-complex',
    title: 'Complex Numbers & Cube Roots of Unity',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Complex Numbers & Cube Roots of Unity Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Complex Numbers & Cube Roots of Unity. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Complex Numbers & Cube Roots of Unity',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Complex Numbers & Cube Roots of Unity',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Complex Numbers & Cube Roots of Unity?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-alg-progressions',
    title: 'AP, GP, HP & Series Shortcuts',
    readTimeMinutes: 8,
    content: [
      { type: 'heading', data: 'AP, GP, HP & Series Shortcuts Overview' },
      { type: 'text', data: 'This is the autogenerated study material for AP, GP, HP & Series Shortcuts. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of AP, GP, HP & Series Shortcuts',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of AP, GP, HP & Series Shortcuts',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying AP, GP, HP & Series Shortcuts?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-alg-binomial',
    title: 'Binomial Theorem & PnC',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Binomial Theorem & PnC Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Binomial Theorem & PnC. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Binomial Theorem & PnC',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Binomial Theorem & PnC',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Binomial Theorem & PnC?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-ai-01',
    title: 'Complex Numbers - Properties and Operations',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Complex Numbers - Properties and Operations Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Complex Numbers - Properties and Operations. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Complex Numbers - Properties and Operations',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Complex Numbers - Properties and Operations',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Complex Numbers - Properties and Operations?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-ai-02',
    title: 'Quadratic Equations - Roots and Discriminant',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Quadratic Equations - Roots and Discriminant Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Quadratic Equations - Roots and Discriminant. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Quadratic Equations - Roots and Discriminant',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Quadratic Equations - Roots and Discriminant',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Quadratic Equations - Roots and Discriminant?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-ai-03',
    title: 'Arithmetic and Geometric Progressions',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Arithmetic and Geometric Progressions Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Arithmetic and Geometric Progressions. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Arithmetic and Geometric Progressions',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Arithmetic and Geometric Progressions',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Arithmetic and Geometric Progressions?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-ai-04',
    title: 'Permutations and Combinations',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Permutations and Combinations Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Permutations and Combinations. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Permutations and Combinations',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Permutations and Combinations',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Permutations and Combinations?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-ai-05',
    title: 'Binomial Theorem and Its Applications',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Binomial Theorem and Its Applications Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Binomial Theorem and Its Applications. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Binomial Theorem and Its Applications',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Binomial Theorem and Its Applications',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Binomial Theorem and Its Applications?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-ai-06',
    title: 'Matrices and Determinants - Properties and Solving',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Matrices and Determinants - Properties and Solving Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Matrices and Determinants - Properties and Solving. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Matrices and Determinants - Properties and Solving',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Matrices and Determinants - Properties and Solving',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Matrices and Determinants - Properties and Solving?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-52',
    title: 'Algebra & Progressions - Advanced Topic 52',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 52 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 52. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 52',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 52',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 52?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-53',
    title: 'Algebra & Progressions - Advanced Topic 53',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 53 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 53. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 53',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 53',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 53?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-56',
    title: 'Algebra & Progressions - Advanced Topic 56',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 56 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 56. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 56',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 56',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 56?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-58',
    title: 'Algebra & Progressions - Advanced Topic 58',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 58 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 58. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 58',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 58',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 58?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-59',
    title: 'Algebra & Progressions - Advanced Topic 59',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 59 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 59. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 59',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 59',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 59?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-62',
    title: 'Algebra & Progressions - Advanced Topic 62',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 62 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 62. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 62',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 62',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 62?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-64',
    title: 'Algebra & Progressions - Advanced Topic 64',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 64 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 64. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 64',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 64',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 64?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-65',
    title: 'Algebra & Progressions - Advanced Topic 65',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 65 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 65. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 65',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 65',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 65?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-68',
    title: 'Algebra & Progressions - Advanced Topic 68',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 68 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 68. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 68',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 68',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 68?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-70',
    title: 'Algebra & Progressions - Advanced Topic 70',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 70 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 70. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 70',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 70',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 70?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-71',
    title: 'Algebra & Progressions - Advanced Topic 71',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 71 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 71. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 71',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 71',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 71?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-74',
    title: 'Algebra & Progressions - Advanced Topic 74',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 74 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 74. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 74',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 74',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 74?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-76',
    title: 'Algebra & Progressions - Advanced Topic 76',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 76 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 76. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 76',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 76',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 76?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-77',
    title: 'Algebra & Progressions - Advanced Topic 77',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 77 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 77. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 77',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 77',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 77?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-80',
    title: 'Algebra & Progressions - Advanced Topic 80',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 80 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 80. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 80',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 80',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 80?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-82',
    title: 'Algebra & Progressions - Advanced Topic 82',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 82 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 82. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 82',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 82',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 82?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-83',
    title: 'Algebra & Progressions - Advanced Topic 83',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 83 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 83. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 83',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 83',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 83?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-86',
    title: 'Algebra & Progressions - Advanced Topic 86',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 86 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 86. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 86',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 86',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 86?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-88',
    title: 'Algebra & Progressions - Advanced Topic 88',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 88 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 88. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 88',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 88',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 88?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-89',
    title: 'Algebra & Progressions - Advanced Topic 89',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 89 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 89. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 89',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 89',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 89?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-92',
    title: 'Algebra & Progressions - Advanced Topic 92',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 92 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 92. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 92',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 92',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 92?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-94',
    title: 'Algebra & Progressions - Advanced Topic 94',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 94 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 94. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 94',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 94',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 94?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-95',
    title: 'Algebra & Progressions - Advanced Topic 95',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 95 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 95. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 95',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 95',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 95?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-algebra-bulk-98',
    title: 'Algebra & Progressions - Advanced Topic 98',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Algebra & Progressions - Advanced Topic 98 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Algebra & Progressions - Advanced Topic 98. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Algebra & Progressions - Advanced Topic 98',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Algebra & Progressions - Advanced Topic 98',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Algebra & Progressions - Advanced Topic 98?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
]
