import { TopicContent } from '../../types'

export const NDA_VECTORS_AUTOGEN: TopicContent[] = [
  {
    id: 'nda-vec-basics',
    title: 'Dot & Cross Products',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Dot & Cross Products Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Dot & Cross Products. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Dot & Cross Products',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Dot & Cross Products',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Dot & Cross Products?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vec-3d',
    title: '3D Geometry: Lines & Planes',
    readTimeMinutes: 15,
    content: [
      { type: 'heading', data: '3D Geometry: Lines & Planes Overview' },
      { type: 'text', data: 'This is the autogenerated study material for 3D Geometry: Lines & Planes. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of 3D Geometry: Lines & Planes',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of 3D Geometry: Lines & Planes',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying 3D Geometry: Lines & Planes?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-ai-01',
    title: 'Vector Basics - Types, Operations and Properties',
    readTimeMinutes: 15,
    content: [
      { type: 'heading', data: 'Vector Basics - Types, Operations and Properties Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Basics - Types, Operations and Properties. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Basics - Types, Operations and Properties',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Basics - Types, Operations and Properties',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Basics - Types, Operations and Properties?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-ai-02',
    title: 'Scalar and Vector Products - Dot and Cross Product',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Scalar and Vector Products - Dot and Cross Product Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Scalar and Vector Products - Dot and Cross Product. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Scalar and Vector Products - Dot and Cross Product',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Scalar and Vector Products - Dot and Cross Product',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Scalar and Vector Products - Dot and Cross Product?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-ai-03',
    title: '3D Geometry - Direction Cosines and Ratios',
    readTimeMinutes: 15,
    content: [
      { type: 'heading', data: '3D Geometry - Direction Cosines and Ratios Overview' },
      { type: 'text', data: 'This is the autogenerated study material for 3D Geometry - Direction Cosines and Ratios. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of 3D Geometry - Direction Cosines and Ratios',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of 3D Geometry - Direction Cosines and Ratios',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying 3D Geometry - Direction Cosines and Ratios?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-ai-04',
    title: 'Equation of a Line and Plane in 3D Space',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Equation of a Line and Plane in 3D Space Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Equation of a Line and Plane in 3D Space. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Equation of a Line and Plane in 3D Space',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Equation of a Line and Plane in 3D Space',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Equation of a Line and Plane in 3D Space?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-ai-05',
    title: 'Applications of Vectors in Geometry',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Applications of Vectors in Geometry Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Applications of Vectors in Geometry. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Applications of Vectors in Geometry',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Applications of Vectors in Geometry',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Applications of Vectors in Geometry?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-51',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 51',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 51 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 51. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 51',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 51',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 51?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-52',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 52',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 52 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 52. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 52',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 52',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 52?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-55',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 55',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 55 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 55. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 55',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 55',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 55?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-57',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 57',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 57 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 57. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 57',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 57',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 57?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-58',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 58',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 58 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 58. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 58',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 58',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 58?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-61',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 61',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 61 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 61. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 61',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 61',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 61?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-63',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 63',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 63 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 63. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 63',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 63',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 63?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-64',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 64',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 64 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 64. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 64',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 64',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 64?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-67',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 67',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 67 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 67. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 67',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 67',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 67?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-69',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 69',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 69 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 69. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 69',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 69',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 69?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-70',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 70',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 70 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 70. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 70',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 70',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 70?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-73',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 73',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 73 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 73. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 73',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 73',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 73?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-75',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 75',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 75 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 75. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 75',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 75',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 75?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-76',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 76',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 76 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 76. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 76',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 76',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 76?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-79',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 79',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 79 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 79. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 79',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 79',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 79?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-81',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 81',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 81 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 81. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 81',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 81',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 81?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-82',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 82',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 82 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 82. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 82',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 82',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 82?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-85',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 85',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 85 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 85. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 85',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 85',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 85?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-87',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 87',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 87 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 87. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 87',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 87',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 87?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-88',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 88',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 88 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 88. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 88',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 88',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 88?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-91',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 91',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 91 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 91. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 91',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 91',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 91?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-93',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 93',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 93 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 93. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 93',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 93',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 93?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-94',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 94',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 94 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 94. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 94',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 94',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 94?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-97',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 97',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 97 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 97. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 97',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 97',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 97?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-vectors-bulk-99',
    title: 'Vector Algebra & 3D Geometry - Advanced Topic 99',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Vector Algebra & 3D Geometry - Advanced Topic 99 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vector Algebra & 3D Geometry - Advanced Topic 99. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vector Algebra & 3D Geometry - Advanced Topic 99',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vector Algebra & 3D Geometry - Advanced Topic 99',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vector Algebra & 3D Geometry - Advanced Topic 99?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
]
