import { TopicContent } from '../../types'

export const NDA_GAT_PHYSICS_AUTOGEN: TopicContent[] = [
  {
    id: 'nda-phys-mechanics',
    title: 'Newton\'s Laws & Work-Energy',
    readTimeMinutes: 15,
    content: [
      { type: 'heading', data: 'Newton\'s Laws & Work-Energy Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Newton\'s Laws & Work-Energy. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Newton\'s Laws & Work-Energy',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Newton\'s Laws & Work-Energy',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Newton\'s Laws & Work-Energy?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-phys-optics',
    title: 'Light: Reflection & Refraction',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Light: Reflection & Refraction Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Light: Reflection & Refraction. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Light: Reflection & Refraction',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Light: Reflection & Refraction',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Light: Reflection & Refraction?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-ai-01',
    title: 'Newton\'s Laws of Motion - Concepts and Numericals',
    readTimeMinutes: 15,
    content: [
      { type: 'heading', data: 'Newton\'s Laws of Motion - Concepts and Numericals Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Newton\'s Laws of Motion - Concepts and Numericals. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Newton\'s Laws of Motion - Concepts and Numericals',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Newton\'s Laws of Motion - Concepts and Numericals',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Newton\'s Laws of Motion - Concepts and Numericals?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-ai-02',
    title: 'Work, Energy and Power - Conservation Laws',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Work, Energy and Power - Conservation Laws Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Work, Energy and Power - Conservation Laws. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Work, Energy and Power - Conservation Laws',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Work, Energy and Power - Conservation Laws',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Work, Energy and Power - Conservation Laws?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-ai-03',
    title: 'Wave Motion - Types, Properties and Sound Waves',
    readTimeMinutes: 18,
    content: [
      { type: 'heading', data: 'Wave Motion - Types, Properties and Sound Waves Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Wave Motion - Types, Properties and Sound Waves. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Wave Motion - Types, Properties and Sound Waves',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Wave Motion - Types, Properties and Sound Waves',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Wave Motion - Types, Properties and Sound Waves?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-ai-04',
    title: 'Optics - Reflection, Refraction and Lenses',
    readTimeMinutes: 20,
    content: [
      { type: 'heading', data: 'Optics - Reflection, Refraction and Lenses Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Optics - Reflection, Refraction and Lenses. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Optics - Reflection, Refraction and Lenses',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Optics - Reflection, Refraction and Lenses',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Optics - Reflection, Refraction and Lenses?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-ai-05',
    title: 'Heat and Thermodynamics - Laws and Applications',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Heat and Thermodynamics - Laws and Applications Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Heat and Thermodynamics - Laws and Applications. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Heat and Thermodynamics - Laws and Applications',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Heat and Thermodynamics - Laws and Applications',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Heat and Thermodynamics - Laws and Applications?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-ai-06',
    title: 'Electricity and Magnetism - Current, Circuits, EMF',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Electricity and Magnetism - Current, Circuits, EMF Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Electricity and Magnetism - Current, Circuits, EMF. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Electricity and Magnetism - Current, Circuits, EMF',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Electricity and Magnetism - Current, Circuits, EMF',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Electricity and Magnetism - Current, Circuits, EMF?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-50',
    title: 'Physics: Mechanics & Waves - Advanced Topic 50',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 50 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 50. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 50',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 50',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 50?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-53',
    title: 'Physics: Mechanics & Waves - Advanced Topic 53',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 53 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 53. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 53',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 53',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 53?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-56',
    title: 'Physics: Mechanics & Waves - Advanced Topic 56',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 56 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 56. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 56',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 56',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 56?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-59',
    title: 'Physics: Mechanics & Waves - Advanced Topic 59',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 59 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 59. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 59',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 59',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 59?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-62',
    title: 'Physics: Mechanics & Waves - Advanced Topic 62',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 62 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 62. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 62',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 62',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 62?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-65',
    title: 'Physics: Mechanics & Waves - Advanced Topic 65',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 65 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 65. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 65',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 65',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 65?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-68',
    title: 'Physics: Mechanics & Waves - Advanced Topic 68',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 68 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 68. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 68',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 68',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 68?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-71',
    title: 'Physics: Mechanics & Waves - Advanced Topic 71',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 71 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 71. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 71',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 71',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 71?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-74',
    title: 'Physics: Mechanics & Waves - Advanced Topic 74',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 74 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 74. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 74',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 74',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 74?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-77',
    title: 'Physics: Mechanics & Waves - Advanced Topic 77',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 77 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 77. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 77',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 77',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 77?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-80',
    title: 'Physics: Mechanics & Waves - Advanced Topic 80',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 80 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 80. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 80',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 80',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 80?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-83',
    title: 'Physics: Mechanics & Waves - Advanced Topic 83',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 83 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 83. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 83',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 83',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 83?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-86',
    title: 'Physics: Mechanics & Waves - Advanced Topic 86',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 86 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 86. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 86',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 86',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 86?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-89',
    title: 'Physics: Mechanics & Waves - Advanced Topic 89',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 89 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 89. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 89',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 89',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 89?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-92',
    title: 'Physics: Mechanics & Waves - Advanced Topic 92',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 92 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 92. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 92',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 92',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 92?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-95',
    title: 'Physics: Mechanics & Waves - Advanced Topic 95',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 95 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 95. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 95',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 95',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 95?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-physics-bulk-98',
    title: 'Physics: Mechanics & Waves - Advanced Topic 98',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Physics: Mechanics & Waves - Advanced Topic 98 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Physics: Mechanics & Waves - Advanced Topic 98. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Physics: Mechanics & Waves - Advanced Topic 98',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Physics: Mechanics & Waves - Advanced Topic 98',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Physics: Mechanics & Waves - Advanced Topic 98?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
]
