import { TopicContent } from '../../types'

export const NDA_GAT_ENGLISH_AUTOGEN: TopicContent[] = [
  {
    id: 'nda-eng-errors',
    title: 'Spotting Errors & Subject-Verb Agreement',
    readTimeMinutes: 8,
    content: [
      { type: 'heading', data: 'Spotting Errors & Subject-Verb Agreement Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Spotting Errors & Subject-Verb Agreement. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Spotting Errors & Subject-Verb Agreement',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Spotting Errors & Subject-Verb Agreement',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Spotting Errors & Subject-Verb Agreement?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-eng-vocab',
    title: 'Vocabulary: Synonyms & Antonyms',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Vocabulary: Synonyms & Antonyms Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vocabulary: Synonyms & Antonyms. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vocabulary: Synonyms & Antonyms',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vocabulary: Synonyms & Antonyms',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vocabulary: Synonyms & Antonyms?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-ai-01',
    title: 'Parts of Speech - Nouns, Verbs, Adjectives, Adverbs',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Parts of Speech - Nouns, Verbs, Adjectives, Adverbs Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Parts of Speech - Nouns, Verbs, Adjectives, Adverbs. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Parts of Speech - Nouns, Verbs, Adjectives, Adverbs',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Parts of Speech - Nouns, Verbs, Adjectives, Adverbs',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Parts of Speech - Nouns, Verbs, Adjectives, Adverbs?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-ai-02',
    title: 'Tenses - Present, Past, Future and Their Forms',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Tenses - Present, Past, Future and Their Forms Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Tenses - Present, Past, Future and Their Forms. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Tenses - Present, Past, Future and Their Forms',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Tenses - Present, Past, Future and Their Forms',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Tenses - Present, Past, Future and Their Forms?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-ai-03',
    title: 'Active and Passive Voice - Rules and Conversion',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Active and Passive Voice - Rules and Conversion Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Active and Passive Voice - Rules and Conversion. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Active and Passive Voice - Rules and Conversion',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Active and Passive Voice - Rules and Conversion',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Active and Passive Voice - Rules and Conversion?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-ai-04',
    title: 'Direct and Indirect Speech - Narration Changes',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Direct and Indirect Speech - Narration Changes Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Direct and Indirect Speech - Narration Changes. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Direct and Indirect Speech - Narration Changes',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Direct and Indirect Speech - Narration Changes',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Direct and Indirect Speech - Narration Changes?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-ai-05',
    title: 'Reading Comprehension - Strategies and Practice',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Reading Comprehension - Strategies and Practice Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Reading Comprehension - Strategies and Practice. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Reading Comprehension - Strategies and Practice',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Reading Comprehension - Strategies and Practice',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Reading Comprehension - Strategies and Practice?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-ai-06',
    title: 'Vocabulary and Synonyms/Antonyms for NDA',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Vocabulary and Synonyms/Antonyms for NDA Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Vocabulary and Synonyms/Antonyms for NDA. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Vocabulary and Synonyms/Antonyms for NDA',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Vocabulary and Synonyms/Antonyms for NDA',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Vocabulary and Synonyms/Antonyms for NDA?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-52',
    title: 'English: Grammar & Comprehension - Advanced Topic 52',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 52 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 52. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 52',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 52',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 52?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-55',
    title: 'English: Grammar & Comprehension - Advanced Topic 55',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 55 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 55. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 55',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 55',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 55?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-58',
    title: 'English: Grammar & Comprehension - Advanced Topic 58',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 58 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 58. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 58',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 58',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 58?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-61',
    title: 'English: Grammar & Comprehension - Advanced Topic 61',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 61 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 61. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 61',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 61',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 61?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-64',
    title: 'English: Grammar & Comprehension - Advanced Topic 64',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 64 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 64. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 64',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 64',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 64?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-67',
    title: 'English: Grammar & Comprehension - Advanced Topic 67',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 67 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 67. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 67',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 67',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 67?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-70',
    title: 'English: Grammar & Comprehension - Advanced Topic 70',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 70 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 70. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 70',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 70',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 70?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-73',
    title: 'English: Grammar & Comprehension - Advanced Topic 73',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 73 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 73. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 73',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 73',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 73?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-76',
    title: 'English: Grammar & Comprehension - Advanced Topic 76',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 76 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 76. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 76',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 76',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 76?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-79',
    title: 'English: Grammar & Comprehension - Advanced Topic 79',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 79 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 79. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 79',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 79',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 79?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-82',
    title: 'English: Grammar & Comprehension - Advanced Topic 82',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 82 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 82. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 82',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 82',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 82?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-85',
    title: 'English: Grammar & Comprehension - Advanced Topic 85',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 85 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 85. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 85',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 85',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 85?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-88',
    title: 'English: Grammar & Comprehension - Advanced Topic 88',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 88 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 88. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 88',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 88',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 88?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-91',
    title: 'English: Grammar & Comprehension - Advanced Topic 91',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 91 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 91. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 91',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 91',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 91?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-94',
    title: 'English: Grammar & Comprehension - Advanced Topic 94',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 94 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 94. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 94',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 94',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 94?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'nda-gat-english-bulk-97',
    title: 'English: Grammar & Comprehension - Advanced Topic 97',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'English: Grammar & Comprehension - Advanced Topic 97 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for English: Grammar & Comprehension - Advanced Topic 97. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of English: Grammar & Comprehension - Advanced Topic 97',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of English: Grammar & Comprehension - Advanced Topic 97',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying English: Grammar & Comprehension - Advanced Topic 97?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
]
