const fs = require('fs');

const perspectives = [
  { key: "Parents' View", templates: [
    "How would your parents describe your approach to handling responsibilities at home?",
    "What qualities do your parents appreciate most about you, and which ones concern them?",
    "Describe how your father or mother would introduce you to their close friend.",
    "In what ways have your parents shaped your values and discipline?",
    "What feedback have your parents given you about your temperament during family disagreements?",
    "How would your parents describe your academic journey and career choices so far?",
    "What do your parents think about your decision-making skills in critical situations?",
    "How does your family perceive your ability to manage stress and pressure?",
    "Describe an instance where your parents expressed pride in your actions.",
    "What concerns, if any, do your parents have about your readiness for a leadership role?",
    "How would your mother describe your emotional maturity to a relative?",
    "What do your parents think about your social circle and its influence on you?",
    "How have your parents reacted to your failures, and what did they advise?",
    "Describe how your parents view your physical fitness and health habits.",
    "What values did your parents instill in you that you still follow today?",
    "How would your parents describe your contribution to household duties?",
    "What does your family think about your ambition to join the armed forces?",
    "How do your parents describe your behavior with elders and authority figures?",
    "In your parents' eyes, how have you changed over the last three years?",
    "What would your parents say is the one thing you need to improve the most?",
    "How do your parents view your ability to balance studies, fitness, and social life?",
    "Describe a value clash you had with your parents and how it was resolved.",
    "What sacrifices have your parents made for you, and how has it shaped your outlook?",
    "How would your father rate your sense of duty towards the family?",
    "What would your parents say about your reaction when things do not go as planned?",
    "How do your parents describe your relationship with your siblings?",
    "What aspect of your personality surprises your parents the most?",
    "How would your parents describe your punctuality and time management?",
    "What do your parents think is your strongest trait for a career in the forces?",
    "Describe how your parents have reacted to your independent decisions.",
    "How would your parents describe your honesty and integrity?",
    "What concerns do your parents have about you living away from home?",
    "How do your parents view your financial responsibility?",
    "What would your mother say about your empathy towards others?",
    "How do your parents describe your reaction to criticism?",
    "What do your parents admire about your determination?",
    "How would your parents describe your communication style?",
    "What do your parents think about your risk-taking ability?",
    "How do your parents view your leadership within the family?",
    "Describe how your parents see your growth from childhood to now.",
    "What would your parents say about your ability to inspire others?",
    "How do your parents perceive your adaptability to new environments?",
    "What do your parents think about your sense of humor?",
    "How would your parents describe your commitment to goals?",
    "What feedback have your parents given about your public speaking?",
    "How do your parents view your respect for traditions and culture?",
    "What would your parents change about your daily routine?",
    "How do your parents describe your mental toughness?",
    "What do your parents think about your volunteering and social work?",
    "How would your parents describe your reliability in tough times?",
    "What character traits do your parents wish you would develop further?",
    "How do your parents see your patriotism and national pride?",
    "What do your parents think about your interpersonal relationships?",
    "How would your parents describe your ability to learn from mistakes?",
    "What do your parents think about your physical courage?",
    "How do your parents view your competitive spirit?",
    "What would your parents say about your ability to work in a team?",
    "How do your parents perceive your emotional intelligence?",
    "What do your parents think about your long-term planning ability?",
    "How would your parents describe your moral compass?"
  ]},
  { key: "Teachers'/Employers' View", templates: [
    "How would your favorite teacher describe your classroom participation and initiative?",
    "What feedback has a teacher or employer given you about your leadership style?",
    "Describe how a professor or boss would rate your ability to work under deadlines.",
    "How would your mentor describe your response to constructive criticism?",
    "What strengths would a teacher highlight about you in a recommendation letter?",
    "How does your employer or teacher view your teamwork and collaboration skills?",
    "Describe what a coach or instructor would say about your perseverance during challenges.",
    "How would a senior colleague describe your problem-solving approach?",
    "What areas of improvement would a teacher point out in your academic performance?",
    "How would your training instructor rate your discipline and consistency?",
    "What would your class teacher say about your influence on your peers?",
    "How does your employer view your punctuality and work ethic?",
    "What feedback have you received about your presentation or communication skills?",
    "How would a teacher describe your curiosity and willingness to learn?",
    "What would your sports coach say about your sportsmanship and fair play?",
    "How does your supervisor view your ability to handle multiple tasks?",
    "Describe how a teacher would rate your analytical thinking abilities.",
    "What would your employer say about your adaptability to new roles?",
    "How would a professor describe your research and independent study habits?",
    "What feedback has a teacher given you about your behavior during group projects?",
    "How would your NCC/NSS coordinator describe your commitment?",
    "What would your practical instructor say about your hands-on skills?",
    "How does your teacher view your growth over the academic year?",
    "What feedback have you received about your time management in assignments?",
    "How would your mentor describe your career readiness?",
    "What would a teacher say about your ability to motivate classmates?",
    "How does your employer describe your initiative-taking behavior?",
    "What areas would your teacher recommend for personal development?",
    "How would your professor describe your ethical standards?",
    "What would a coach say about your mental toughness during competitions?",
    "How does your teacher view your respect for rules and authority?",
    "What feedback has your employer given about your decision-making?",
    "How would your teacher describe your creative thinking?",
    "What would your mentor say about your professional growth?",
    "How does your instructor view your technical competence?",
    "What would a teacher highlight as your biggest achievement?",
    "How does your employer describe your conflict resolution skills?",
    "What areas of leadership would your teacher say you excel in?",
    "How would your coach describe your team spirit?",
    "What would your professor say about your intellectual curiosity?",
    "How does your teacher view your community service involvement?",
    "What feedback has your employer given about your reliability?",
    "How would your instructor rate your physical fitness standards?",
    "What would your teacher say about your written expression skills?",
    "How does your mentor view your strategic thinking ability?",
    "What feedback have you received about your classroom leadership?",
    "How would your employer describe your organizational skills?",
    "What would a teacher say about your ability to handle failure?",
    "How does your coach view your training discipline?",
    "What would your professor say about your seminar participation?",
    "How does your teacher view your general knowledge and awareness?",
    "What feedback has your employer given about your customer relations?",
    "How would your instructor describe your learning attitude?",
    "What would your mentor say about your emotional stability at work?",
    "How does your teacher view your planning and execution skills?",
    "What feedback have you received about your cooperation with authorities?",
    "How would your employer rate your loyalty and dedication?",
    "What would a teacher say about your peer influence?",
    "How does your coach view your competitiveness?",
    "What would your professor say about your innovation potential?"
  ]},
  { key: "Friends' View", templates: [
    "How would your closest friend describe your behavior during a group crisis?",
    "What do your friends say about your loyalty and trustworthiness?",
    "How do your friends perceive your ability to manage conflicts within the group?",
    "Describe how your friend would introduce you to a new acquaintance.",
    "What would your best friend say is your most annoying habit and your best quality?",
    "How do your friends view your role during group adventures or outings?",
    "What would your college friends say about your influence on the group's decisions?",
    "How do your peers perceive your sense of humor and social skills?",
    "What would your roommate or hostel mate say about living with you?",
    "How do your friends describe your reaction when someone is in trouble?",
    "What would your friends say about your competitive nature in sports?",
    "How do your peers view your honesty and straightforwardness?",
    "What would your friend say about your behavior at social gatherings?",
    "How do your friends describe your approach to new challenges?",
    "What do your friends think about your risk-taking tendencies?",
    "How would your friends describe your emotional support during tough times?",
    "What would your peers say about your organizational skills for events?",
    "How do your friends view your assertiveness in group discussions?",
    "What would your close friend say about your handling of peer pressure?",
    "How do your friends perceive your balance between fun and responsibility?",
    "What would your friends say about your ability to keep secrets?",
    "How do your peers describe your generosity and sharing?",
    "What do your friends think about your reaction to success?",
    "How would your friends describe your patience with others?",
    "What would your peers say about your adventurous spirit?",
    "How do your friends view your reliability for group tasks?",
    "What would your roommate say about your daily habits?",
    "How do your friends describe your attitude towards juniors?",
    "What do your peers think about your ability to apologize?",
    "How would your friends describe your handling of disagreements?",
    "What would your close friend say about your ambition?",
    "How do your friends view your cultural sensitivity?",
    "What do your peers think about your physical fitness commitment?",
    "How would your friends describe your response to criticism from peers?",
    "What would your friends say about your initiative in social activities?",
    "How do your peers describe your ability to make new friends?",
    "What do your friends think about your decision to join the forces?",
    "How would your friends describe your sense of justice?",
    "What would your peers say about your ability to forgive?",
    "How do your friends view your influence on younger students?",
    "What would your close friend say about your personal growth?",
    "How do your peers describe your courage in everyday life?",
    "What do your friends think about your self-discipline?",
    "How would your friends describe your public behavior?",
    "What would your peers say about your enthusiasm for learning?",
    "How do your friends view your commitment to promises?",
    "What do your friends think about your negotiation skills?",
    "How would your friends describe your reaction under pressure?",
    "What would your close friend say about your biggest strength?",
    "How do your peers describe your contribution to the friend group?",
    "What do your friends think about your leadership outside academics?",
    "How would your friends describe your moral standards?",
    "What would your peers say about your ability to motivate others?",
    "How do your friends view your handling of jealousy or envy?",
    "What do your friends think about your time management?",
    "How would your friends describe your listening skills?",
    "What would your peers say about your conflict mediation?",
    "How do your friends view your creativity?",
    "What would your close friend say about your biggest weakness?",
    "How do your peers describe your overall personality?"
  ]},
  { key: "Self-Assessment", templates: [
    "Identify three core strengths that make you a suitable officer candidate and explain each briefly.",
    "What is your biggest weakness, and what concrete steps are you taking to overcome it?",
    "Describe a situation where you demonstrated leadership without being asked.",
    "How do you handle failure, and what was the most significant lesson a failure taught you?",
    "What motivates you to pursue a career in the armed forces?",
    "Describe your approach to making decisions under uncertainty or pressure.",
    "What are the values you refuse to compromise on, regardless of the situation?",
    "How do you prioritize when you have multiple important tasks at the same time?",
    "Describe a challenging situation where you had to take an unpopular decision.",
    "How do you maintain your physical and mental fitness routinely?",
    "What role do you naturally take in a team, and why?",
    "Describe your strategy for dealing with people who disagree with you.",
    "What is the toughest decision you have made in the last two years?",
    "How do you cope with loneliness or being away from your support system?",
    "What achievement are you most proud of and why?",
    "Describe how you prepare for situations that involve risk or danger.",
    "What would you change about yourself if you could?",
    "How do you stay motivated during long, monotonous tasks?",
    "Describe your philosophy on duty, discipline, and sacrifice.",
    "What do you consider your most important contribution to your community?",
    "How do you handle ethical dilemmas where no option seems ideal?",
    "Describe your approach to continuous self-improvement.",
    "What fears do you need to overcome to become a better leader?",
    "How do you manage your emotions during high-stress situations?",
    "What makes you different from other candidates?",
    "Describe your ideal self five years from now.",
    "How do you balance ambition with humility?",
    "What life experience has most prepared you for military service?",
    "Describe your approach to building trust with new people.",
    "How do you respond when your authority is challenged?",
    "What is your definition of courage?",
    "Describe a time you went beyond your comfort zone.",
    "How do you handle boredom and routine?",
    "What role does physical fitness play in your daily life?",
    "Describe your understanding of duty to the nation.",
    "How do you deal with unfair treatment or injustice?",
    "What is your biggest regret and what did you learn from it?",
    "Describe your approach to mentoring or guiding juniors.",
    "How do you react when plans fail unexpectedly?",
    "What personal habits contribute to your success?",
    "Describe your relationship with discipline and structure.",
    "How do you handle success without becoming complacent?",
    "What does integrity mean to you in practice?",
    "Describe your method for staying calm under fire.",
    "How do you evaluate your own performance objectively?",
    "What sacrifices are you willing to make for your career?",
    "Describe your approach to learning new skills quickly.",
    "How do you handle responsibility for others' well-being?",
    "What is your greatest fear about military life?",
    "Describe how you maintain work-life balance.",
    "How do you deal with people who underestimate you?",
    "What legacy do you want to leave behind?",
    "Describe your approach to building resilience.",
    "How do you stay updated with current affairs and developments?",
    "What is your vision for your contribution to national security?",
    "Describe a moral principle you would never violate.",
    "How do you handle situations where you lack expertise?",
    "What does selfless service mean to you?",
    "Describe your biggest intellectual challenge and how you handled it.",
    "How do you maintain your mental health and emotional well-being?"
  ]},
  { key: "Improvement Areas", templates: [
    "What is one weakness you have actively worked to improve in the last year?",
    "Describe a skill you lack but believe is essential for an officer.",
    "What feedback have you received repeatedly that you still struggle to act on?",
    "How are you working to improve your physical endurance and stamina?",
    "What communication gap do you need to bridge, and how are you doing it?",
    "Describe an area where your confidence is low and what steps you are taking.",
    "What habits do you need to break to become a more effective leader?",
    "How are you improving your ability to work with people from diverse backgrounds?",
    "What emotional reaction do you need to control better, and how?",
    "Describe your plan for improving your general knowledge and current affairs awareness.",
    "What aspect of teamwork do you find most challenging?",
    "How are you developing your strategic thinking abilities?",
    "What time management issues are you working to resolve?",
    "Describe your plan to improve your physical fitness score.",
    "What leadership skill do you need to develop further?",
    "How are you working on your patience and tolerance?",
    "What academic area requires your immediate attention?",
    "Describe your approach to improving your decision-making speed.",
    "What social skill are you actively developing?",
    "How are you improving your ability to accept constructive criticism?",
    "What aspect of discipline do you struggle with most?",
    "Describe your plan for becoming more assertive without being aggressive.",
    "What technical skill gap are you currently addressing?",
    "How are you improving your ability to handle uncertainty?",
    "What emotional intelligence area needs your focus?",
    "Describe your approach to building better study habits.",
    "What conflict resolution skill are you developing?",
    "How are you working to improve your public speaking?",
    "What aspect of organizational behavior do you need to understand better?",
    "Describe your plan to improve your crisis management abilities.",
    "What personal bias are you trying to overcome?",
    "How are you improving your listening skills?",
    "What writing skill needs your immediate attention?",
    "Describe your approach to developing more empathy.",
    "What negotiation skill are you working on?",
    "How are you building better relationships with authority figures?",
    "What stress management technique are you adopting?",
    "Describe your plan to improve your analytical thinking.",
    "What aspect of self-awareness are you developing?",
    "How are you improving your ability to delegate tasks?",
    "What personal quality do your friends say needs improvement?",
    "Describe your approach to managing anger or frustration.",
    "What planning skill do you need to refine?",
    "How are you working on your attention to detail?",
    "What aspect of courage do you need to develop?",
    "Describe your plan for improving your networking skills.",
    "What cultural sensitivity gap are you addressing?",
    "How are you working on your financial discipline?",
    "What aspect of commitment do you struggle with?",
    "Describe your approach to improving your moral reasoning.",
    "What health habit are you trying to establish?",
    "How are you developing your creative problem-solving?",
    "What aspect of reliability do you need to improve?",
    "Describe your plan for building mental toughness.",
    "What cooperative skill needs your attention?",
    "How are you improving your ability to inspire others?",
    "What aspect of adaptability are you working on?",
    "Describe your approach to overcoming procrastination.",
    "What quality of perseverance do you need to strengthen?",
    "How are you developing your sense of responsibility?"
  ]}
];

const focusAreasPool = {
  "Parents' View": [
    ["responsibility","discipline","emotional maturity"],
    ["family values","obedience","respect for elders"],
    ["decision-making","independence","self-reliance"],
    ["temperament","patience","conflict resolution"],
    ["academic performance","career focus","ambition"],
    ["physical fitness","health consciousness","endurance"],
    ["financial responsibility","planning","resource management"],
    ["social behavior","peer influence","character"],
    ["honesty","integrity","moral values"],
    ["adaptability","resilience","mental strength"],
    ["communication","expression","listening"],
    ["patriotism","national pride","service orientation"],
    ["time management","punctuality","consistency"],
    ["leadership within family","initiative","proactiveness"],
    ["empathy","compassion","emotional intelligence"]
  ],
  "Teachers'/Employers' View": [
    ["academic rigor","intellectual curiosity","classroom participation"],
    ["leadership","initiative","team management"],
    ["work ethic","punctuality","dedication"],
    ["problem-solving","analytical thinking","logical reasoning"],
    ["communication skills","presentation","articulation"],
    ["teamwork","collaboration","peer support"],
    ["discipline","consistency","follow-through"],
    ["creativity","innovation","original thinking"],
    ["adaptability","learning agility","flexibility"],
    ["technical competence","practical skills","application"],
    ["ethical conduct","professional integrity","accountability"],
    ["time management","deadline adherence","prioritization"],
    ["research skills","independent study","self-directed learning"],
    ["mentorship","peer guidance","knowledge sharing"],
    ["organizational skills","planning","execution"]
  ],
  "Friends' View": [
    ["loyalty","trustworthiness","dependability"],
    ["humor","social skills","approachability"],
    ["crisis management","composure","quick thinking"],
    ["generosity","empathy","emotional support"],
    ["adventurous spirit","risk-taking","courage"],
    ["conflict resolution","mediation","fairness"],
    ["influence","motivation","inspiration"],
    ["honesty","straightforwardness","transparency"],
    ["team spirit","cooperation","inclusiveness"],
    ["fun-loving","energy","enthusiasm"],
    ["listening skills","understanding","patience"],
    ["competitive nature","sportsmanship","fair play"],
    ["reliability","consistency","commitment"],
    ["cultural sensitivity","respect","open-mindedness"],
    ["personal growth","self-improvement","maturity"]
  ],
  "Self-Assessment": [
    ["self-awareness","introspection","personal growth"],
    ["leadership potential","decision-making","authority"],
    ["emotional regulation","stress management","composure"],
    ["physical fitness","endurance","health discipline"],
    ["values","integrity","moral compass"],
    ["motivation","drive","goal orientation"],
    ["risk assessment","courage","calculated boldness"],
    ["adaptability","flexibility","open-mindedness"],
    ["communication","expression","influence"],
    ["teamwork","collaboration","cooperation"],
    ["discipline","routine","structure"],
    ["resilience","perseverance","mental toughness"],
    ["strategic thinking","planning","foresight"],
    ["empathy","compassion","service orientation"],
    ["continuous learning","curiosity","intellectual growth"]
  ],
  "Improvement Areas": [
    ["weakness identification","action plan","progress tracking"],
    ["skill development","training","practice"],
    ["habit formation","consistency","discipline"],
    ["emotional control","patience","temperament"],
    ["communication gap","expression","clarity"],
    ["physical fitness improvement","endurance building","stamina"],
    ["knowledge expansion","reading","awareness"],
    ["confidence building","assertiveness","self-belief"],
    ["time management","prioritization","efficiency"],
    ["leadership development","initiative","decision-making"],
    ["social skills","networking","relationship building"],
    ["stress management","coping mechanisms","mental health"],
    ["academic improvement","study habits","focus"],
    ["conflict resolution","negotiation","diplomacy"],
    ["adaptability","flexibility","change management"]
  ]
};

const result = {
  metadata: {
    total_prompts: 300,
    total_sets: 60,
    time_limit_minutes: 15,
    words_per_section: "150-200",
    version: "2.0",
    description: "60 unique Self Description practice sets for SSB preparation"
  },
  sets: []
};

for (let i = 0; i < 60; i++) {
  const set = {
    set_id: i + 1,
    name: `Set ${String(i + 1).padStart(2, '0')}`,
    prompts: perspectives.map((p, pi) => {
      const templates = p.templates;
      const prompt = templates[i % templates.length];
      const focusPool = focusAreasPool[p.key];
      const focus = focusPool[i % focusPool.length];
      return {
        perspective: p.key,
        prompt: prompt,
        focus_areas: focus
      };
    })
  };
  result.sets.push(set);
}

fs.writeFileSync('src/data/sd_60_sets.json', JSON.stringify(result, null, 2));
console.log('Generated ' + result.sets.length + ' unique SD sets with ' + (result.sets.length * 5) + ' total prompts');
