const fs = require('fs');

// GD Topics - 120 unique topics across 6 categories
const gdTopics = [
  // Technology & Cyber (20)
  {topic:"Should AI be used in military decision-making?",category:"Technology & Cyber",key_points:["Ethical risks of autonomous weapons","Speed vs human judgment","Current global AI arms race","India's DRDO AI initiatives"]},
  {topic:"Is social media a threat to national security?",category:"Technology & Cyber",key_points:["Misinformation and propaganda warfare","Data privacy concerns","Foreign influence operations","Regulation vs freedom of speech"]},
  {topic:"Cybersecurity as the fifth domain of warfare",category:"Technology & Cyber",key_points:["State-sponsored cyber attacks","Critical infrastructure vulnerability","India's cyber command structure","International cyber norms"]},
  {topic:"Digital India: Achievement or hype?",category:"Technology & Cyber",key_points:["Rural internet penetration statistics","UPI and digital payments success","Digital divide challenges","E-governance implementation"]},
  {topic:"Should India develop its own operating system and tech ecosystem?",category:"Technology & Cyber",key_points:["Strategic autonomy in technology","Cost and feasibility challenges","Current dependence on US-China tech","BharOS and indigenous efforts"]},
  {topic:"5G and its implications for defense and society",category:"Technology & Cyber",key_points:["Enhanced battlefield communications","IoT and smart city integration","Chinese equipment security concerns","Spectrum allocation challenges"]},
  {topic:"Deepfakes and synthetic media: How should India respond?",category:"Technology & Cyber",key_points:["Election manipulation risks","Legal framework gaps","Detection technology development","Impact on judicial evidence"]},
  {topic:"Space technology for national defense",category:"Technology & Cyber",key_points:["ASAT capability demonstration","Satellite surveillance systems","Space debris concerns","Dual-use technology potential"]},
  {topic:"Should cryptocurrencies be banned in India?",category:"Technology & Cyber",key_points:["Terrorism financing risks","Blockchain technology benefits","RBI digital rupee initiative","Global regulatory approaches"]},
  {topic:"Quantum computing and its impact on defense",category:"Technology & Cyber",key_points:["Encryption breaking potential","India's quantum computing mission","Military communication security","Research investment needs"]},
  {topic:"Drones in modern warfare and civilian use",category:"Technology & Cyber",key_points:["Counter-drone technology","Agricultural applications","Privacy and surveillance concerns","India's drone policy framework"]},
  {topic:"Ethical hacking and India's cyber defense capability",category:"Technology & Cyber",key_points:["Bug bounty programs","Cyber warrior training","Offensive vs defensive capabilities","Public-private partnerships"]},
  {topic:"Internet shutdowns: Security measure or rights violation?",category:"Technology & Cyber",key_points:["Kashmir shutdown precedent","Economic impact data","Alternative security measures","Supreme Court rulings"]},
  {topic:"Robotics in Indian manufacturing and defense",category:"Technology & Cyber",key_points:["Job displacement concerns","Unmanned ground vehicles","Make in India robotics push","Skill development needs"]},
  {topic:"Data sovereignty and cross-border data flows",category:"Technology & Cyber",key_points:["Personal Data Protection Bill","Server localization debate","Trade agreement implications","National security vs business needs"]},
  {topic:"Electric vehicles and India's energy security",category:"Technology & Cyber",key_points:["Battery technology challenges","Charging infrastructure gaps","Lithium import dependency","FAME scheme effectiveness"]},
  {topic:"Biometric surveillance and privacy in India",category:"Technology & Cyber",key_points:["Aadhaar security concerns","Facial recognition deployment","Right to privacy judgment","Surveillance state risks"]},
  {topic:"Indian IT industry: From outsourcing to innovation",category:"Technology & Cyber",key_points:["Product vs service company shift","Startup ecosystem growth","Brain drain reversal trends","Global competitiveness"]},
  {topic:"Satellite internet and bridging the digital divide",category:"Technology & Cyber",key_points:["Starlink and OneWeb in India","Rural connectivity potential","Spectrum sharing challenges","ISRO's broadband satellite plans"]},
  {topic:"Artificial intelligence in healthcare: Promise and peril",category:"Technology & Cyber",key_points:["Diagnostic accuracy improvements","Data privacy in health records","Rural healthcare delivery","Ethical AI in treatment decisions"]},
  // Defense & Security (20)
  {topic:"Agnipath scheme: Reform or gamble?",category:"Defense & Security",key_points:["Short-service model benefits","Veteran rehabilitation concerns","Youth employment impact","Military readiness questions"]},
  {topic:"Should India have a Chief of Defense Staff with more powers?",category:"Defense & Security",key_points:["Theaterisation of armed forces","Inter-service coordination","Democratic civilian control","Global CDS models comparison"]},
  {topic:"India's two-front war challenge: China and Pakistan",category:"Defense & Security",key_points:["Force deployment strategy","Nuclear deterrence dynamics","Diplomatic balancing act","Infrastructure development on borders"]},
  {topic:"Women in combat roles: Progress and challenges",category:"Defense & Security",key_points:["Permanent commission achievements","Physical standards debate","Global examples of integration","Cultural mindset changes needed"]},
  {topic:"Is India's nuclear doctrine still relevant?",category:"Defense & Security",key_points:["No-first-use policy debate","Credible minimum deterrence","Pakistan's tactical nuclear weapons","Disarmament pressure"]},
  {topic:"Maritime security in the Indo-Pacific",category:"Defense & Security",key_points:["Chinese naval expansion","QUAD alliance significance","Indian Ocean Region strategy","Blue water navy development"]},
  {topic:"Defense indigenization: Progress and gaps",category:"Defense & Security",key_points:["HAL Tejas achievements","DRDO project delays","Private sector participation","Technology transfer challenges"]},
  {topic:"Counter-terrorism strategy post-Pulwama",category:"Defense & Security",key_points:["Surgical strike doctrine","Intelligence sharing mechanisms","De-radicalization programs","Cross-border terrorism response"]},
  {topic:"Theaterisation of Indian armed forces",category:"Defense & Security",key_points:["Joint commands concept","Service-specific resistance","Operational efficiency gains","Budget allocation reforms"]},
  {topic:"Border infrastructure: Road to security",category:"Defense & Security",key_points:["BRO project acceleration","LAC infrastructure gaps","Strategic tunnel projects","Environmental impact balance"]},
  {topic:"Defense budget: Is India spending enough?",category:"Defense & Security",key_points:["GDP percentage comparison globally","Revenue vs capital expenditure","Modernization backlog","Pension burden impact"]},
  {topic:"Role of paramilitary forces in internal security",category:"Defense & Security",key_points:["CRPF deployment challenges","Naxal affected areas","Border guarding efficiency","Force multiplier technology"]},
  {topic:"India's missile defense shield",category:"Defense & Security",key_points:["BMD program development","S-400 acquisition significance","Indigenous vs imported systems","Multi-layered defense strategy"]},
  {topic:"Cyber warfare readiness of Indian armed forces",category:"Defense & Security",key_points:["Defence Cyber Agency capabilities","Critical infrastructure protection","Offensive cyber operations","Training and personnel"]},
  {topic:"Veterans' welfare and rehabilitation in India",category:"Defense & Security",key_points:["OROP implementation issues","Skill transition programs","Mental health support","Corporate sector integration"]},
  {topic:"India-US defense partnership evolution",category:"Defense & Security",key_points:["LEMOA, COMCASA, BECA agreements","Technology transfer potential","Strategic autonomy concerns","Joint exercises significance"]},
  {topic:"Insurgency in Northeast India: Current status",category:"Defense & Security",key_points:["AFSPA debate continues","Peace accord progress","Development as counter-insurgency","Cross-border safe havens"]},
  {topic:"Submarine capability and underwater warfare",category:"Defense & Security",key_points:["Project 75 India progress","Nuclear submarine fleet","Underwater domain awareness","Anti-submarine warfare gaps"]},
  {topic:"Role of Indian armed forces in disaster management",category:"Defense & Security",key_points:["NDRF vs military deployment","Flood rescue operations","COVID-19 response contribution","Dual-use capability development"]},
  {topic:"Private military companies: Should India allow them?",category:"Defense & Security",key_points:["Global PMC market analysis","Accountability concerns","Cost-effectiveness debate","Strategic outsourcing limits"]},
  // Geopolitics & International Relations (20)
  {topic:"India's permanent seat on UN Security Council",category:"Geopolitics & International Relations",key_points:["Reform proposals and opposition","P5 veto power dynamics","India's contribution to UN peacekeeping","Alternative reform models"]},
  {topic:"China's Belt and Road Initiative: Opportunity or threat?",category:"Geopolitics & International Relations",key_points:["Debt trap diplomacy allegations","CPEC through PoK","India's counter-connectivity projects","ASEAN countries' experience"]},
  {topic:"Russia-Ukraine conflict: Lessons for India",category:"Geopolitics & International Relations",key_points:["India's diplomatic balancing act","Energy security implications","Defense equipment dependency","Nuclear escalation risks"]},
  {topic:"QUAD: Asian NATO or loose partnership?",category:"Geopolitics & International Relations",key_points:["Military cooperation scope","Economic agenda potential","China's containment perception","India's strategic autonomy"]},
  {topic:"India's neighborhood first policy: Success or failure?",category:"Geopolitics & International Relations",key_points:["Sri Lanka crisis response","Nepal relations fluctuation","Bangladesh migration issue","Chinese influence in South Asia"]},
  {topic:"Middle East conflicts and India's diplomatic tightrope",category:"Geopolitics & International Relations",key_points:["Energy dependency management","Diaspora safety concerns","Arms trade relationships","Abraham Accords impact"]},
  {topic:"Should India join RCEP?",category:"Geopolitics & International Relations",key_points:["Trade deficit concerns with China","Market access opportunities","Manufacturing sector impact","Strategic trade alignment"]},
  {topic:"Africa: India's next strategic frontier",category:"Geopolitics & International Relations",key_points:["Chinese influence competition","Development partnership model","Resource access strategy","Cultural and diaspora ties"]},
  {topic:"India-Pakistan relations: Is dialogue possible?",category:"Geopolitics & International Relations",key_points:["Kashmir issue centrality","Cross-border terrorism linkage","Trade and people-to-people contact","Third-party mediation debate"]},
  {topic:"Climate diplomacy and India's position",category:"Geopolitics & International Relations",key_points:["Net-zero target commitments","Developed vs developing nation debate","Green technology transfer","Loss and damage funding"]},
  {topic:"BRICS expansion: Counterweight to Western dominance?",category:"Geopolitics & International Relations",key_points:["New Development Bank role","De-dollarization agenda","Internal contradictions","Geopolitical realignment"]},
  {topic:"Taiwan strait crisis and implications for India",category:"Geopolitics & International Relations",key_points:["One-China policy position","Trade route disruption risks","Semiconductor supply chain","Military preparedness lessons"]},
  {topic:"India's Act East policy effectiveness",category:"Geopolitics & International Relations",key_points:["ASEAN connectivity projects","Northeast as gateway","Economic integration progress","Security cooperation with Vietnam"]},
  {topic:"Arctic geopolitics and India's interests",category:"Geopolitics & International Relations",key_points:["Northern Sea Route access","Scientific research stations","Resource extraction opportunities","Environmental protection advocacy"]},
  {topic:"Multilateralism vs bilateralism in Indian foreign policy",category:"Geopolitics & International Relations",key_points:["UN system effectiveness","Regional groupings value","Issue-based coalitions","Great power relationships"]},
  {topic:"Global refugee crisis and India's responsibilities",category:"Geopolitics & International Relations",key_points:["Rohingya and Afghan refugees","No refugee convention ratification","Citizenship Amendment Act","Humanitarian vs security balance"]},
  {topic:"De-dollarization and India's trade in rupees",category:"Geopolitics & International Relations",key_points:["Rupee trade agreements","SWIFT alternative development","Sanctions evasion concerns","Currency internationalization"]},
  {topic:"Space race 2.0: Competition or cooperation?",category:"Geopolitics & International Relations",key_points:["ISRO's commercial launch success","Artemis Accords participation","Space militarization concerns","International space law reform"]},
  {topic:"Indian diaspora as soft power",category:"Geopolitics & International Relations",key_points:["Political influence in key countries","Remittance contribution","Brain drain vs brain gain","Cultural diplomacy potential"]},
  {topic:"Global food security and India's role",category:"Geopolitics & International Relations",key_points:["Wheat export ban controversy","Agricultural technology sharing","Climate change impact on farming","International food aid policies"]},
  // Society & National Issues (20)
  {topic:"Uniform Civil Code: Need of the hour?",category:"Society & National Issues",key_points:["Constitutional directive principle","Religious freedom concerns","Gender justice arguments","Implementation challenges"]},
  {topic:"Reservation policy: Time for reform?",category:"Society & National Issues",key_points:["Creamy layer implementation","Economic basis vs caste basis","50% cap and exceptions","Merit vs social justice debate"]},
  {topic:"Mental health crisis among Indian youth",category:"Society & National Issues",key_points:["Suicide rate statistics","Social media impact","Access to mental health services","Stigma reduction efforts"]},
  {topic:"Education system reform: NEP 2020 impact",category:"Society & National Issues",key_points:["Mother tongue instruction debate","Vocational education integration","Research funding increase","Implementation at state level"]},
  {topic:"Farmer protests and agricultural reforms",category:"Society & National Issues",key_points:["MSP guarantee demand","Corporate farming concerns","Small farmer vulnerability","Global agricultural models"]},
  {topic:"Population control: Should India have a policy?",category:"Society & National Issues",key_points:["Demographic dividend vs burden","State-level population laws","Women's empowerment approach","Economic development correlation"]},
  {topic:"Judicial reforms needed in India",category:"Society & National Issues",key_points:["Case pendency crisis","Collegium vs NJAC","Fast-track courts effectiveness","Access to justice in rural areas"]},
  {topic:"Caste system: Is it weakening or strengthening?",category:"Society & National Issues",key_points:["Urban vs rural dynamics","Inter-caste marriage trends","Political mobilization on caste","Economic mobility data"]},
  {topic:"Media freedom and responsible journalism in India",category:"Society & National Issues",key_points:["Press freedom index ranking","Paid news phenomenon","Social media journalism","Self-regulation vs government control"]},
  {topic:"Urban-rural divide: How to bridge it?",category:"Society & National Issues",key_points:["Infrastructure gap statistics","Migration patterns","Smart village concept","Telecom and internet penetration"]},
  {topic:"Drug menace in India: Prevention and cure",category:"Society & National Issues",key_points:["Punjab and Northeast drug corridor","Youth vulnerability","Rehabilitation infrastructure","Cross-border smuggling routes"]},
  {topic:"Should voting be made compulsory in India?",category:"Society & National Issues",key_points:["Low voter turnout concerns","Democratic participation importance","Enforcement challenges","International examples"]},
  {topic:"Child labor and trafficking: Ground reality",category:"Society & National Issues",key_points:["Legislative framework gaps","Rehabilitation programs","Economic root causes","Role of civil society"]},
  {topic:"Water crisis in India: Solutions and strategies",category:"Society & National Issues",key_points:["Groundwater depletion data","River interlinking project","Rainwater harvesting mandate","Industrial water usage"]},
  {topic:"Gender equality in the Indian armed forces",category:"Society & National Issues",key_points:["Supreme Court directives","Combat role expansion","Infrastructure requirements","Cultural shift needed"]},
  {topic:"Corruption: Can India become corruption-free?",category:"Society & National Issues",key_points:["Lokpal and CBI effectiveness","Digital governance impact","Whistleblower protection","Political will assessment"]},
  {topic:"Right to privacy in the digital age",category:"Society & National Issues",key_points:["Puttaswamy judgment significance","Surveillance state concerns","Data protection legislation","Corporate data misuse"]},
  {topic:"Sports culture in India: Beyond cricket",category:"Society & National Issues",key_points:["Olympic medal tally analysis","Grassroots infrastructure","Corporate sponsorship role","Khelo India scheme impact"]},
  {topic:"Elderly care and aging population challenges",category:"Society & National Issues",key_points:["Joint family system decline","Healthcare infrastructure needs","Pension and social security","Technology for elder care"]},
  {topic:"Language policy and national unity",category:"Society & National Issues",key_points:["Three-language formula","Hindi imposition resistance","English as link language","Regional language preservation"]},
  // Economy & Environment (20)
  {topic:"Make in India: Has it delivered?",category:"Economy & Environment",key_points:["Manufacturing GDP share trends","FDI inflow data","Ease of doing business ranking","China+1 strategy opportunity"]},
  {topic:"Privatization of public sector: Boon or bane?",category:"Economy & Environment",key_points:["Air India sale precedent","Banking sector reform","Strategic sector definition","Employee welfare concerns"]},
  {topic:"Climate change and India's development dilemma",category:"Economy & Environment",key_points:["Energy transition timeline","Green hydrogen mission","Carbon credit trading","Just transition for coal workers"]},
  {topic:"Gig economy: Future of work in India?",category:"Economy & Environment",key_points:["Social security for gig workers","Platform company regulation","Skill development alignment","Labor law reform needs"]},
  {topic:"India's semiconductor ambitions",category:"Economy & Environment",key_points:["Fab manufacturing challenges","Supply chain vulnerabilities","Government incentive programs","Global competition for talent"]},
  {topic:"Cryptocurrency vs digital rupee",category:"Economy & Environment",key_points:["RBI's CBDC framework","Taxation of crypto assets","Financial inclusion potential","Technology infrastructure needs"]},
  {topic:"Renewable energy: Can India achieve its targets?",category:"Economy & Environment",key_points:["Solar and wind capacity growth","Grid integration challenges","Storage technology gaps","International climate commitments"]},
  {topic:"Infrastructure development vs environmental protection",category:"Economy & Environment",key_points:["EIA dilution concerns","Forest clearance process","Compensatory afforestation","Sustainable development models"]},
  {topic:"India's trade deficit: Causes and solutions",category:"Economy & Environment",key_points:["Oil import dependency","Electronics import reduction","Export promotion schemes","FTA negotiation strategy"]},
  {topic:"Startup India: Building the next Silicon Valley?",category:"Economy & Environment",key_points:["Unicorn growth trajectory","Funding winter challenges","Tier-2 city ecosystem","Deep tech vs consumer tech"]},
  {topic:"Plastic pollution and India's response",category:"Economy & Environment",key_points:["Single-use plastic ban enforcement","Alternative material development","Waste management infrastructure","Extended producer responsibility"]},
  {topic:"Food processing industry: Untapped potential",category:"Economy & Environment",key_points:["Post-harvest loss reduction","Cold chain infrastructure","Export market development","Farmer income improvement"]},
  {topic:"Universal Basic Income for India",category:"Economy & Environment",key_points:["Fiscal feasibility analysis","Existing subsidy replacement","Pilot project results","Inflation impact concerns"]},
  {topic:"Blue economy: India's maritime economic potential",category:"Economy & Environment",key_points:["Sagarmala project progress","Deep-sea mining prospects","Sustainable fishing practices","Port-led industrialization"]},
  {topic:"Air pollution crisis in Indian cities",category:"Economy & Environment",key_points:["Stubble burning solutions","Vehicle emission standards","Industrial pollution control","Health impact costs"]},
  {topic:"Tourism as economic driver for India",category:"Economy & Environment",key_points:["Heritage site conservation","Eco-tourism potential","Northeast tourism development","Infrastructure and safety needs"]},
  {topic:"India's banking sector challenges",category:"Economy & Environment",key_points:["NPA resolution progress","Digital banking adoption","Financial inclusion depth","Public vs private bank performance"]},
  {topic:"Circular economy: India's waste management future",category:"Economy & Environment",key_points:["Waste-to-energy projects","Recycling infrastructure","Behavioral change requirements","Extended producer responsibility"]},
  {topic:"Skill development and employability in India",category:"Economy & Environment",key_points:["Skill India mission outcomes","Industry-academia gap","Vocational training quality","Demographic dividend window"]},
  {topic:"Organic farming: Viable alternative?",category:"Economy & Environment",key_points:["Sikkim organic state model","Yield reduction concerns","Market premium access","Chemical fertilizer subsidy reform"]},
  // Abstract & Philosophical (20)
  {topic:"Is patriotism the same as nationalism?",category:"Abstract & Philosophical",key_points:["Definitional differences","Historical examples","Inclusive vs exclusive identity","Modern nation-state context"]},
  {topic:"Can violence ever be justified for a cause?",category:"Abstract & Philosophical",key_points:["Self-defense doctrine","Freedom struggle examples","Just war theory","Gandhian non-violence relevance"]},
  {topic:"Is democracy the best form of government?",category:"Abstract & Philosophical",key_points:["Churchill's famous quote analysis","Efficiency vs representation","Informed electorate requirement","Authoritarian development models"]},
  {topic:"Success: Is it about the journey or the destination?",category:"Abstract & Philosophical",key_points:["Process vs outcome orientation","Learning from failure","Defining personal success","Societal pressure on achievement"]},
  {topic:"Should ethics change with changing times?",category:"Abstract & Philosophical",key_points:["Moral relativism debate","Universal human values","Cultural context influence","Technology-driven ethical questions"]},
  {topic:"Individual freedom vs collective responsibility",category:"Abstract & Philosophical",key_points:["COVID lockdown experience","Libertarian vs communitarian views","Constitutional fundamental rights","Duty as reciprocal to rights"]},
  {topic:"Is competition necessary for progress?",category:"Abstract & Philosophical",key_points:["Cooperation as alternative model","Evolutionary perspective","Economic competition effects","Education system implications"]},
  {topic:"Power corrupts: Is this always true?",category:"Abstract & Philosophical",key_points:["Lord Acton's maxim analysis","Servant leadership concept","Institutional checks on power","Historical counter-examples"]},
  {topic:"Is privacy a luxury in the 21st century?",category:"Abstract & Philosophical",key_points:["Surveillance capitalism","Nothing to hide argument","Human dignity connection","Democratic freedom linkage"]},
  {topic:"Duty or ambition: What should drive a soldier?",category:"Abstract & Philosophical",key_points:["Selfless service ideal","Career progression motivation","National interest framework","Personal growth within service"]},
  {topic:"Is tradition an obstacle to progress?",category:"Abstract & Philosophical",key_points:["Cultural preservation value","Innovation and disruption","Selective modernization","Identity and rootedness"]},
  {topic:"Can artificial intelligence have consciousness?",category:"Abstract & Philosophical",key_points:["Chinese room argument","Turing test limitations","Ethical implications of sentient AI","Human uniqueness debate"]},
  {topic:"Is social media making us more or less connected?",category:"Abstract & Philosophical",key_points:["Superficial vs deep connections","Echo chamber effects","Global awareness increase","Mental health impact"]},
  {topic:"Forgiveness: Weakness or strength?",category:"Abstract & Philosophical",key_points:["Psychological benefits","Justice vs mercy balance","National reconciliation examples","Personal growth through forgiveness"]},
  {topic:"Is there such a thing as a just war?",category:"Abstract & Philosophical",key_points:["International humanitarian law","Proportionality principle","Civilian protection imperative","Pre-emptive strike ethics"]},
  {topic:"Should leaders be feared or loved?",category:"Abstract & Philosophical",key_points:["Machiavelli vs modern leadership","Respect as middle ground","Military leadership styles","Situational leadership theory"]},
  {topic:"Is meritocracy a myth?",category:"Abstract & Philosophical",key_points:["Structural inequality factors","Equal opportunity vs equal outcome","Education as equalizer","Social mobility data"]},
  {topic:"Happiness: Is it a choice or a circumstance?",category:"Abstract & Philosophical",key_points:["Positive psychology research","Hedonic adaptation","Material vs experiential happiness","Stoic philosophy application"]},
  {topic:"Risk-taking: Recklessness or courage?",category:"Abstract & Philosophical",key_points:["Calculated risk framework","Military decision-making context","Entrepreneurial risk parallels","Cost of inaction analysis"]},
  {topic:"Can one person change the world?",category:"Abstract & Philosophical",key_points:["Great man theory critique","Systemic change requirements","Butterfly effect concept","Leadership as catalyst"]}
];

// Build GD sets (2 topics each)
const gdResult = {
  metadata: { total_topics: 120, total_sets: 60, time_per_discussion_minutes: 20, version: "2.0" },
  sets: []
};

for (let i = 0; i < 60; i++) {
  gdResult.sets.push({
    set_id: i + 1,
    name: `Set ${String(i + 1).padStart(2, '0')}`,
    topics: [gdTopics[i * 2], gdTopics[i * 2 + 1]]
  });
}

fs.writeFileSync('src/data/gd_60_sets.json', JSON.stringify(gdResult, null, 2));
console.log('GD: Generated ' + gdResult.sets.length + ' sets with ' + (gdResult.sets.length * 2) + ' topics');

// Lecturette Topics - 240 unique topics
const lecturetteCategories = ["Technology & Cyber","Defense & Security","Geopolitics & International Relations","Society & National Issues","Economy & Environment","Abstract & Philosophical"];

const lecturetteTopicBank = [
  // Tech (40)
  {t:"Artificial Intelligence in Everyday Life",c:"Technology & Cyber",kp:["Smart assistants","Recommendation algorithms","Healthcare diagnostics","Ethical concerns"]},
  {t:"Blockchain Beyond Cryptocurrency",c:"Technology & Cyber",kp:["Supply chain transparency","Smart contracts","Voting systems","Land registry"]},
  {t:"Internet of Things: Connected World",c:"Technology & Cyber",kp:["Smart cities","Industrial automation","Privacy risks","Healthcare monitoring"]},
  {t:"Cloud Computing and Data Sovereignty",c:"Technology & Cyber",kp:["Government cloud adoption","Cross-border data flows","Security challenges","Cost optimization"]},
  {t:"Augmented Reality in Education",c:"Technology & Cyber",kp:["Interactive learning","Medical training","Cost barriers","Content development"]},
  {t:"3D Printing Revolution",c:"Technology & Cyber",kp:["Manufacturing disruption","Medical implants","Housing construction","IP challenges"]},
  {t:"Autonomous Vehicles: Road to the Future",c:"Technology & Cyber",kp:["Safety statistics","Legal liability","Infrastructure needs","Job displacement"]},
  {t:"Nanotechnology Applications",c:"Technology & Cyber",kp:["Medical nano-robots","Material science advances","Water purification","Environmental risks"]},
  {t:"Big Data Analytics in Governance",c:"Technology & Cyber",kp:["Predictive policing","Healthcare resource allocation","Tax compliance","Privacy protection"]},
  {t:"Wearable Technology and Health",c:"Technology & Cyber",kp:["Fitness tracking accuracy","Continuous health monitoring","Data sharing ethics","Military applications"]},
  {t:"Gene Editing and CRISPR Technology",c:"Technology & Cyber",kp:["Disease elimination potential","Designer baby ethics","Agricultural applications","Regulatory framework"]},
  {t:"Virtual Reality in Military Training",c:"Technology & Cyber",kp:["Combat simulation","Cost reduction","PTSD treatment","Limitations and risks"]},
  {t:"Digital Twin Technology",c:"Technology & Cyber",kp:["Industrial applications","Urban planning","Healthcare simulation","Cost-benefit analysis"]},
  {t:"Edge Computing and Its Applications",c:"Technology & Cyber",kp:["Real-time processing","IoT device support","Security advantages","5G integration"]},
  {t:"Biometric Authentication Systems",c:"Technology & Cyber",kp:["Fingerprint vs facial recognition","Spoofing vulnerabilities","Privacy concerns","Government adoption"]},
  {t:"Green Technology Innovations",c:"Technology & Cyber",kp:["Solar cell efficiency","Wind turbine advances","Battery storage","Carbon capture"]},
  {t:"Telemedicine: Healthcare at a Distance",c:"Technology & Cyber",kp:["Rural access improvement","Regulatory challenges","Quality assurance","COVID-19 acceleration"]},
  {t:"Social Engineering and Cyber Fraud",c:"Technology & Cyber",kp:["Phishing techniques","Psychological manipulation","Prevention strategies","Financial impact"]},
  {t:"Open Source Software Movement",c:"Technology & Cyber",kp:["Community-driven development","Security through transparency","Government adoption","Business models"]},
  {t:"Digital Literacy for All",c:"Technology & Cyber",kp:["Rural skill development","Senior citizen inclusion","Vernacular content","Cyber safety awareness"]},
  {t:"Robotics in Agriculture",c:"Technology & Cyber",kp:["Precision farming","Labor shortage solution","Cost considerations","Indian suitability"]},
  {t:"Ethical AI: Bias and Fairness",c:"Technology & Cyber",kp:["Algorithmic discrimination","Training data bias","Accountability frameworks","Diversity in AI teams"]},
  {t:"Smart Cities Mission: Progress Review",c:"Technology & Cyber",kp:["100 cities target","Infrastructure digitization","Citizen participation","Sustainability focus"]},
  {t:"Fintech Revolution in India",c:"Technology & Cyber",kp:["UPI global model","Micro-lending platforms","Regulatory sandbox","Financial inclusion impact"]},
  {t:"Quantum Internet and Secure Communications",c:"Technology & Cyber",kp:["Quantum key distribution","Unbreakable encryption","Current research status","Military applications"]},
  {t:"Brain-Computer Interface Technology",c:"Technology & Cyber",kp:["Medical rehabilitation","Neuralink developments","Ethical boundaries","Military potential"]},
  {t:"Metaverse: Future of Digital Interaction",c:"Technology & Cyber",kp:["Virtual economies","Social isolation risks","Business applications","Technology requirements"]},
  {t:"Cyberbullying and Online Safety",c:"Technology & Cyber",kp:["Youth vulnerability","Legal remedies","Platform responsibility","Prevention education"]},
  {t:"Technology in Disaster Management",c:"Technology & Cyber",kp:["Early warning systems","Drone-based surveys","Communication resilience","AI prediction models"]},
  {t:"India's Semiconductor Mission",c:"Technology & Cyber",kp:["Fab manufacturing strategy","Global supply chain position","Talent development","Investment requirements"]},
  {t:"Precision Medicine and Genomics",c:"Technology & Cyber",kp:["Personalized treatment","Genetic testing ethics","Cost accessibility","Indian genome project"]},
  {t:"Digital Payments Security",c:"Technology & Cyber",kp:["Fraud prevention","Two-factor authentication","Consumer protection","Cross-border transactions"]},
  {t:"Space Tourism: Science or Luxury?",c:"Technology & Cyber",kp:["Commercial space companies","Environmental impact","Democratization of space","ISRO's commercial potential"]},
  {t:"Internet Governance and Net Neutrality",c:"Technology & Cyber",kp:["TRAI regulations","Content throttling","Digital rights","Global governance models"]},
  {t:"E-Waste Management Challenges",c:"Technology & Cyber",kp:["Toxic material disposal","Recycling infrastructure","Extended producer responsibility","Informal sector role"]},
  {t:"Hyperloop and Future Transportation",c:"Technology & Cyber",kp:["Technical feasibility","Indian route proposals","Cost analysis","Environmental benefits"]},
  {t:"Lab-Grown Meat and Food Technology",c:"Technology & Cyber",kp:["Environmental benefits","Cultural acceptance","Nutritional comparison","Regulatory approval"]},
  {t:"Digital Detox: Need of Modern Times",c:"Technology & Cyber",kp:["Screen addiction statistics","Cognitive impact","Workplace productivity","Mindfulness practices"]},
  {t:"Synthetic Biology and Its Promise",c:"Technology & Cyber",kp:["Biofuel production","Disease treatment","Biosecurity risks","Ethical guidelines"]},
  {t:"Tech-Enabled Farming in India",c:"Technology & Cyber",kp:["Soil health monitoring","Weather prediction","Market access platforms","Smallholder adoption barriers"]},
  // Defense (40)
  {t:"Indian Navy: Guardian of the Seas",c:"Defense & Security",kp:["Aircraft carrier program","Submarine fleet modernization","Indo-Pacific presence","Maritime domain awareness"]},
  {t:"Special Forces of India",c:"Defense & Security",kp:["Para SF operations","MARCOS capabilities","NSG role","Training and selection"]},
  {t:"Mountain Warfare: Challenges and Strategy",c:"Defense & Security",kp:["High altitude operations","Equipment requirements","Ladakh deployment","Acclimatization protocols"]},
  {t:"India's Nuclear Triad Capability",c:"Defense & Security",kp:["Agni missile series","SSBN Arihant class","Strategic Forces Command","Deterrence credibility"]},
  {t:"Integrated Battle Groups Concept",c:"Defense & Security",kp:["Cold Start doctrine evolution","Quick mobilization","Pakistan's response","Operational challenges"]},
  {t:"Indian Air Force Modernization",c:"Defense & Security",kp:["Rafale induction impact","AMCA development","Squadron strength gap","AESA radar program"]},
  {t:"Role of NCC in Nation Building",c:"Defense & Security",kp:["Youth leadership development","Disaster relief contribution","Social integration","NCC directorate reforms"]},
  {t:"Left Wing Extremism in India",c:"Defense & Security",kp:["Red corridor mapping","SAMADHAN strategy","Development approach","Security operations"]},
  {t:"India's Defense Export Potential",c:"Defense & Security",kp:["BrahMos export deals","Tejas for friendly nations","Policy framework","Competition with global players"]},
  {t:"Chemical, Biological, Radiological and Nuclear Defense",c:"Defense & Security",kp:["Threat assessment","Detection capabilities","Decontamination procedures","International conventions"]},
  {t:"Joint Military Exercises: Significance",c:"Defense & Security",kp:["Interoperability building","Diplomatic signaling","Best practices exchange","Recent exercise highlights"]},
  {t:"Artificial Intelligence in Defense",c:"Defense & Security",kp:["Autonomous weapon systems","Intelligence analysis","Logistics optimization","Ethical guidelines"]},
  {t:"Indian Coast Guard: Silent Sentinel",c:"Defense & Security",kp:["Maritime border patrol","Fishermen protection","Anti-smuggling operations","Pollution control"]},
  {t:"Electronic Warfare Capabilities",c:"Defense & Security",kp:["Spectrum dominance","Radar jamming","Communication security","Indigenous development"]},
  {t:"Military Logistics and Supply Chain",c:"Defense & Security",kp:["Forward area provisioning","Cold chain challenges","Ammunition management","Technology integration"]},
  {t:"India's Strategic Airlift Capability",c:"Defense & Security",kp:["C-17 Globemaster fleet","Humanitarian aid delivery","Rapid deployment","Multi-role transport aircraft"]},
  {t:"Psychological Warfare in Modern Conflicts",c:"Defense & Security",kp:["Information operations","Social media manipulation","Counter-narrative strategies","Historical examples"]},
  {t:"Indian Military History: Lessons for Today",c:"Defense & Security",kp:["1971 war strategy","Kargil conflict lessons","Siachen operations","Battle of Longewala"]},
  {t:"Unmanned Combat Vehicles",c:"Defense & Security",kp:["Drone swarm technology","Armed UAV development","Counter-UAS systems","Legal and ethical issues"]},
  {t:"Military Intelligence: Art and Science",c:"Defense & Security",kp:["HUMINT vs SIGINT","Satellite reconnaissance","Open source intelligence","Coordination mechanisms"]},
  {t:"India's Ballistic Missile Defense",c:"Defense & Security",kp:["PAD and AAD systems","S-400 integration","Layered defense concept","Technology maturity"]},
  {t:"Defense Procurement Reforms",c:"Defense & Security",kp:["DAP 2020 changes","Make in India priority","Offset policy","Strategic partnership model"]},
  {t:"Role of Army in Counter-Insurgency",c:"Defense & Security",kp:["Hearts and minds approach","Operation Sadbhavana","Minimum force principle","Civil-military cooperation"]},
  {t:"India's Military Diplomacy",c:"Defense & Security",kp:["Defense attaches network","UN peacekeeping contribution","Training foreign military","Arms trade relationships"]},
  {t:"Integrated Air Defense System",c:"Defense & Security",kp:["Multi-layer concept","Radar network coverage","Surface-to-air missiles","Air defense identification zones"]},
  {t:"Veterans in National Development",c:"Defense & Security",kp:["Corporate sector placement","Entrepreneurship support","Policy advocacy role","Mentoring young officers"]},
  {t:"Combat Engineering in Modern Warfare",c:"Defense & Security",kp:["Mine warfare","Bridge laying capability","Obstacle creation","Rapid infrastructure"]},
  {t:"Military Medicine and Battlefield Healthcare",c:"Defense & Security",kp:["Golden hour concept","Evacuation protocols","PTSD management","Telemedicine in field"]},
  {t:"Information Warfare in 21st Century",c:"Defense & Security",kp:["Fake news as weapon","Social media operations","Attribution challenges","Democratic resilience"]},
  {t:"India's Overseas Military Bases Debate",c:"Defense & Security",kp:["Djibouti facility","Indian Ocean presence","Strategic necessity","Non-alignment evolution"]},
  {t:"Night Vision and Thermal Imaging Technology",c:"Defense & Security",kp:["Gen-4 systems","Border surveillance","Indigenous development","Cost reduction strategies"]},
  {t:"Military Space Command",c:"Defense & Security",kp:["Defence Space Agency","Space situational awareness","Anti-satellite capability","Space-based communication"]},
  {t:"Terrain Analysis in Military Operations",c:"Defense & Security",kp:["GIS and remote sensing","Riverine operations","Desert warfare","Jungle warfare"]},
  {t:"Indian Army's Corps of Signals",c:"Defense & Security",kp:["Secure communication networks","Electronic warfare role","Digital army transformation","Software defined radios"]},
  {t:"Amphibious Operations Capability",c:"Defense & Security",kp:["Island territory defense","Andaman Nicobar deployment","Landing ships and craft","Joint forces integration"]},
  {t:"Military Ethics and Laws of Armed Conflict",c:"Defense & Security",kp:["Geneva Conventions","Rules of engagement","Proportionality principle","War crimes accountability"]},
  {t:"Artillery Modernization of Indian Army",c:"Defense & Security",kp:["Dhanush and Vajra systems","Guided munitions","Fire control technology","Korean K9 induction"]},
  {t:"Civil-Military Relations in India",c:"Defense & Security",kp:["Constitutional framework","Political control mechanisms","Professional military advice","Historical tension points"]},
  {t:"Indian Navy's Carrier Battle Groups",c:"Defense & Security",kp:["INS Vikrant commissioning","Air wing composition","Escort vessel requirements","Power projection capability"]},
  {t:"Disaster Relief: Military's Force Multiplier Role",c:"Defense & Security",kp:["Kerala floods response","COVID hospital setup","Engineering capability","International HADR"]},
  // Geopolitics (40)
  ...Array.from({length:40}, (_, i) => {
    const topics = [
      {t:"Rise of China: Implications for World Order",c:"Geopolitics & International Relations",kp:["Economic dominance strategy","Military modernization pace","Belt and Road expansion","Debt trap diplomacy"]},
      {t:"India-Japan Strategic Partnership",c:"Geopolitics & International Relations",kp:["Economic cooperation","Nuclear deal significance","Maritime security","2+2 dialogue mechanism"]},
      {t:"United Nations Reform: Urgency and Roadblocks",c:"Geopolitics & International Relations",kp:["Security Council expansion","Veto power reform","Peacekeeping reform","Financing challenges"]},
      {t:"India's Vaccine Diplomacy",c:"Geopolitics & International Relations",kp:["COVID-19 distribution","Soft power projection","Manufacturing capability","WHO partnership"]},
      {t:"South China Sea Dispute",c:"Geopolitics & International Relations",kp:["Freedom of navigation","Artificial island building","UNCLOS application","India's position"]},
      {t:"Energy Security in Indian Context",c:"Geopolitics & International Relations",kp:["Oil import dependency reduction","Strategic petroleum reserves","Renewable energy transition","Nuclear power expansion"]},
      {t:"Indo-Pacific Concept: Evolving Framework",c:"Geopolitics & International Relations",kp:["Free and open Indo-Pacific","Maritime cooperation","Economic dimension","Security architecture"]},
      {t:"Afghanistan After US Withdrawal",c:"Geopolitics & International Relations",kp:["Taliban governance","Regional security impact","India's development investment","Terrorism safe haven risk"]},
      {t:"SCO: India's Engagement Strategy",c:"Geopolitics & International Relations",kp:["Counter-terrorism cooperation","Central Asian connectivity","China-Pakistan factor","Economic potential"]},
      {t:"Water Wars: India's Transboundary River Disputes",c:"Geopolitics & International Relations",kp:["Indus Water Treaty stress","Brahmaputra dam concerns","Ganges water sharing","Climate change impact"]},
      {t:"Non-Aligned Movement in Current Context",c:"Geopolitics & International Relations",kp:["Historical relevance","Strategic autonomy concept","Multi-alignment approach","Developing world leadership"]},
      {t:"Nuclear Non-Proliferation and India",c:"Geopolitics & International Relations",kp:["NPT status","NSG membership quest","CTBT position","Responsible nuclear power"]},
      {t:"India-France Defense Partnership",c:"Geopolitics & International Relations",kp:["Rafale deal significance","Submarine technology","Space cooperation","Indian Ocean partnership"]},
      {t:"Maldives: India's Island Neighbor",c:"Geopolitics & International Relations",kp:["India First policy","Chinese influence counter","Tourism and trade","Maritime security"]},
      {t:"International Criminal Court and India",c:"Geopolitics & International Relations",kp:["Non-member status reason","War crimes accountability","Sovereignty concerns","Selective justice criticism"]},
      {t:"India-Australia Strategic Convergence",c:"Geopolitics & International Relations",kp:["ECTA trade agreement","Maritime cooperation","Chinese factor","Diaspora connections"]},
      {t:"Horn of Africa: Strategic Significance for India",c:"Geopolitics & International Relations",kp:["Anti-piracy operations","Trade route security","Djibouti facility","China's base proximity"]},
      {t:"India's Role in G20 Leadership",c:"Geopolitics & International Relations",kp:["Presidency achievements","Climate finance advocacy","Digital public infrastructure","Voice of Global South"]},
      {t:"Emerging Multi-Polar World Order",c:"Geopolitics & International Relations",kp:["US-China rivalry","Middle power strategies","Regional organizations","India's positioning"]},
      {t:"SAARC: Revival or Replacement?",c:"Geopolitics & International Relations",kp:["Pakistan as obstacle","BIMSTEC alternative","Sub-regional groupings","Trade integration potential"]},
      {t:"India-Israel Defense Cooperation",c:"Geopolitics & International Relations",kp:["Weapons procurement","Technology transfer","Intelligence sharing","Palestine policy balance"]},
      {t:"Central Asian Geopolitics and India",c:"Geopolitics & International Relations",kp:["INSTC corridor","Energy resources","Chabahar port route","Cultural historical ties"]},
      {t:"Sanctions as Foreign Policy Tool",c:"Geopolitics & International Relations",kp:["Effectiveness debate","Secondary sanctions impact","India's position","Economic warfare implications"]},
      {t:"Pacific Islands: New Geopolitical Battleground",c:"Geopolitics & International Relations",kp:["Climate change vulnerability","Chinese checkbook diplomacy","India's FIPIC initiative","Strategic location value"]},
      {t:"India-UK Free Trade Agreement",c:"Geopolitics & International Relations",kp:["Post-Brexit opportunity","Migration provisions","Service sector access","Historical relationship evolution"]},
      {t:"Indian Ocean Rim Association",c:"Geopolitics & International Relations",kp:["Blue economy focus","Maritime security","Trade facilitation","Disaster risk management"]},
      {t:"India-Bangladesh Relations Transformation",c:"Geopolitics & International Relations",kp:["Water sharing agreements","Connectivity projects","Border management","Rohingya issue"]},
      {t:"Global Governance Reform Agenda",c:"Geopolitics & International Relations",kp:["IMF quota reform","World Bank restructuring","WTO dispute resolution","Representation equity"]},
      {t:"India and ASEAN: 30 Years of Partnership",c:"Geopolitics & International Relations",kp:["Trade integration","Connectivity projects","Maritime cooperation","Cultural exchanges"]},
      {t:"Geopolitics of Rare Earth Minerals",c:"Geopolitics & International Relations",kp:["Chinese monopoly","Supply chain diversification","Strategic reserves","Recycling technology"]},
      {t:"India-Gulf Cooperation Council Relations",c:"Geopolitics & International Relations",kp:["Energy partnership","Diaspora welfare","Investment flows","Security cooperation"]},
      {t:"International Humanitarian Law Evolution",c:"Geopolitics & International Relations",kp:["Cyber warfare rules","Autonomous weapons regulation","Non-state actors","Climate refugees"]},
      {t:"India-Canada Relations: Opportunities and Tensions",c:"Geopolitics & International Relations",kp:["Trade potential","Khalistan issue","Student migration","Arctic cooperation"]},
      {t:"Small Island Developing States and India",c:"Geopolitics & International Relations",kp:["Climate finance","Capacity building","Solar alliance","Maritime domain cooperation"]},
      {t:"India in the Arctic Council",c:"Geopolitics & International Relations",kp:["Observer status activities","Scientific research","Northern Sea Route","Resource access"]},
      {t:"Digital Silk Road: China's Tech Expansion",c:"Geopolitics & International Relations",kp:["5G infrastructure export","Surveillance technology","Data governance","India's counter-strategy"]},
      {t:"India-Russia Relations in Changing World",c:"Geopolitics & International Relations",kp:["Defense dependency evolution","Energy cooperation","Technology transfer","Multi-polar world vision"]},
      {t:"Global Health Security Architecture",c:"Geopolitics & International Relations",kp:["Pandemic preparedness","WHO reform","Vaccine equity","India's pharmaceutical role"]},
      {t:"Responsible AI Governance: Global Frameworks",c:"Geopolitics & International Relations",kp:["EU AI Act influence","India's AI strategy","Cross-border regulation","Military AI limitations"]},
      {t:"Outer Space Treaty: Need for Update?",c:"Geopolitics & International Relations",kp:["Space resource mining","Military use restrictions","Orbital debris management","Commercial activities regulation"]}
    ];
    return topics[i];
  }),
  // Society (40)
  ...Array.from({length:40}, (_, i) => {
    const topics = [
      {t:"Youth Empowerment in India",c:"Society & National Issues",kp:["Skill development programs","Political participation","Entrepreneurship encouragement","Mental health support"]},
      {t:"Role of Women in Indian Military",c:"Society & National Issues",kp:["Combat role milestones","Glass ceiling challenges","Training equality","Global comparisons"]},
      {t:"Right to Education: Ground Reality",c:"Society & National Issues",kp:["Enrollment vs learning outcomes","Teacher quality crisis","Digital education divide","Budget allocation"]},
      {t:"Social Media and Democracy",c:"Society & National Issues",kp:["Information democratization","Fake news challenge","Political mobilization","Platform accountability"]},
      {t:"Substance Abuse Among Youth",c:"Society & National Issues",kp:["Prevalence statistics","Root cause analysis","Rehabilitation models","Preventive education"]},
      {t:"Road Safety in India",c:"Society & National Issues",kp:["Accident statistics","Enforcement challenges","Infrastructure design","Behavioral change campaigns"]},
      {t:"Tribal Development and Rights",c:"Society & National Issues",kp:["Forest Rights Act","Cultural preservation","Development model","Displacement issues"]},
      {t:"Role of NGOs in Indian Development",c:"Society & National Issues",kp:["Service delivery gap filling","Accountability concerns","FCRA restrictions","Partnership with government"]},
      {t:"Urbanization Challenges in India",c:"Society & National Issues",kp:["Slum proliferation","Water and sanitation","Transportation congestion","Smart city solutions"]},
      {t:"Disability Rights and Inclusion",c:"Society & National Issues",kp:["RPwD Act implementation","Accessible infrastructure","Employment quota","Attitude change needed"]},
      {t:"Communal Harmony in India",c:"Society & National Issues",kp:["Constitutional secularism","Interfaith dialogue","Media responsibility","Historical coexistence"]},
      {t:"Prison Reform in India",c:"Society & National Issues",kp:["Overcrowding crisis","Undertrial population","Rehabilitation focus","Model prison manual"]},
      {t:"Freedom of Speech: Limits and Responsibilities",c:"Society & National Issues",kp:["Constitutional provisions","Hate speech boundaries","Self-censorship trend","International comparisons"]},
      {t:"National Service for Youth",c:"Society & National Issues",kp:["Character building","Social cohesion","Skill development","International models"]},
      {t:"Impact of Migration on Indian Society",c:"Society & National Issues",kp:["Rural to urban shift","Remittance economy","Cultural assimilation","Social security portability"]},
      {t:"Elderly Care in Modern India",c:"Society & National Issues",kp:["Aging demographics","Healthcare needs","Pension adequacy","Technology solutions"]},
      {t:"Sports as Character Builder",c:"Society & National Issues",kp:["Discipline and teamwork","Competitive spirit","Physical fitness","Leadership development"]},
      {t:"Sanitation and Public Health",c:"Society & National Issues",kp:["Swachh Bharat outcomes","Open defecation statistics","Waste management","Behavioral change"]},
      {t:"Child Marriage: Ending the Practice",c:"Society & National Issues",kp:["Legal framework","Poverty linkage","Education solution","Community engagement"]},
      {t:"Ethics in Public Life",c:"Society & National Issues",kp:["Political accountability","Bureaucratic integrity","Whistleblower protection","Citizens' role"]},
      {t:"Indian Languages: Preservation vs Modernization",c:"Society & National Issues",kp:["Endangered languages","Technology in local languages","Literary traditions","Education policy"]},
      {t:"Volunteerism and Community Service",c:"Society & National Issues",kp:["NSS and NCC contribution","Corporate volunteering","Disaster response","Social bonding"]},
      {t:"Mental Health Awareness in India",c:"Society & National Issues",kp:["Stigma reduction","Professional shortage","Workplace wellness","Government initiatives"]},
      {t:"Organ Donation Awareness",c:"Society & National Issues",kp:["Donation statistics","Legal framework","Religious and cultural barriers","Awareness campaigns"]},
      {t:"Traffic Management in Indian Cities",c:"Society & National Issues",kp:["Public transport development","Parking solutions","Pedestrian safety","Technology integration"]},
      {t:"Heritage Conservation in India",c:"Society & National Issues",kp:["ASI capacity","Private sector role","Tourism potential","Community involvement"]},
      {t:"Quality of Higher Education in India",c:"Society & National Issues",kp:["Global ranking position","Faculty shortage","Research output","Industry connection"]},
      {t:"River Conservation and Rejuvenation",c:"Society & National Issues",kp:["Namami Gange progress","Industrial pollution","Sewage treatment","Community participation"]},
      {t:"Animal Welfare and Rights",c:"Society & National Issues",kp:["Stray dog management","Wildlife protection","Animal testing alternatives","Dairy industry practices"]},
      {t:"Electoral Reforms in India",c:"Society & National Issues",kp:["State funding of elections","Criminalization of politics","EVM security","One nation one election"]},
      {t:"Civic Education and Responsible Citizenship",c:"Society & National Issues",kp:["Rights and duties balance","Environmental responsibility","Democratic participation","Community engagement"]},
      {t:"Child Nutrition and Stunting",c:"Society & National Issues",kp:["ICDS effectiveness","Mid-day meal impact","Micronutrient deficiency","POSHAN Abhiyaan"]},
      {t:"Digital Education: Post-COVID Reality",c:"Society & National Issues",kp:["Device accessibility","Learning outcome measurement","Teacher training needs","Hybrid model adoption"]},
      {t:"Blood Donation and Voluntary Culture",c:"Society & National Issues",kp:["Voluntary vs replacement donation","Blood bank infrastructure","Thalassemia management","Awareness strategies"]},
      {t:"Public-Private Partnership in Education",c:"Society & National Issues",kp:["Quality improvement","Accountability mechanisms","Equity concerns","Successful models"]},
      {t:"Cooperative Movement in India",c:"Society & National Issues",kp:["Amul success model","Credit cooperatives","Agriculture cooperatives","Government role"]},
      {t:"Role of Libraries in Knowledge Society",c:"Society & National Issues",kp:["Digital library initiatives","Community learning centers","Reading habit decline","Open access movement"]},
      {t:"Environmental Education for Youth",c:"Society & National Issues",kp:["Curriculum integration","Eco-clubs","Nature conservation","Sustainable lifestyle"]},
      {t:"Cultural Diversity as National Strength",c:"Society & National Issues",kp:["Unity in diversity","Festival celebrations","Cross-cultural understanding","National integration"]},
      {t:"Responsible Use of Technology by Youth",c:"Society & National Issues",kp:["Screen time management","Cyberbullying prevention","Digital citizenship","Creative applications"]}
    ];
    return topics[i];
  }),
  // Economy (40)
  ...Array.from({length:40}, (_, i) => {
    const topics = [
      {t:"Indian Railways Modernization",c:"Economy & Environment",kp:["Bullet train project","Station redevelopment","Safety improvements","Freight corridor"]},
      {t:"MSMEs: Backbone of Indian Economy",c:"Economy & Environment",kp:["Employment generation","Credit access challenges","Technology adoption","Export potential"]},
      {t:"Green Hydrogen Mission",c:"Economy & Environment",kp:["Production technology","Cost competitiveness","Industrial applications","Export opportunity"]},
      {t:"Insurance Penetration in India",c:"Economy & Environment",kp:["Life vs general insurance","Crop insurance effectiveness","Health insurance expansion","Micro-insurance models"]},
      {t:"Smart Agriculture Practices",c:"Economy & Environment",kp:["Precision farming","Drip irrigation adoption","Soil health management","Market linkage"]},
      {t:"Coastal Economy Development",c:"Economy & Environment",kp:["Sagarmala project","Port modernization","Fishing industry","Coastal tourism"]},
      {t:"Nuclear Energy: India's Clean Power Option",c:"Economy & Environment",kp:["Thorium fuel cycle","Safety record","Cost competitiveness","Public acceptance"]},
      {t:"Waste-to-Wealth: Circular Economy Model",c:"Economy & Environment",kp:["Composting and recycling","Biogas generation","Construction material from waste","Job creation"]},
      {t:"Real Estate Sector Reforms",c:"Economy & Environment",kp:["RERA impact","Affordable housing push","Construction technology","Smart cities integration"]},
      {t:"Logistics Sector in India",c:"Economy & Environment",kp:["National Logistics Policy","Multimodal transport","Cost reduction strategies","Technology integration"]},
      {t:"Micro-Finance and Financial Inclusion",c:"Economy & Environment",kp:["Self-help group model","Jan Dhan Yojana","Mobile banking growth","Over-indebtedness risks"]},
      {t:"Solar Energy Revolution in India",c:"Economy & Environment",kp:["Installed capacity growth","International Solar Alliance","Manufacturing push","Rooftop solar potential"]},
      {t:"Fiscal Federalism in India",c:"Economy & Environment",kp:["GST revenue sharing","Finance Commission recommendations","State debt concerns","Central grants criteria"]},
      {t:"Pharmaceutical Industry: India's Global Role",c:"Economy & Environment",kp:["Generic medicines supply","API dependency on China","Research and innovation","Quality standards"]},
      {t:"National Highway Development",c:"Economy & Environment",kp:["Bharatmala project","Expressway network","Toll collection reform","Road safety engineering"]},
      {t:"Sustainable Fashion Industry",c:"Economy & Environment",kp:["Fast fashion environmental cost","Handloom and khadi revival","Textile waste recycling","Cotton farming sustainability"]},
      {t:"Inland Waterway Development",c:"Economy & Environment",kp:["Cargo transportation potential","Environmental benefits","Infrastructure investment","Success stories"]},
      {t:"India's Defence Industrial Corridor",c:"Economy & Environment",kp:["Tamil Nadu and UP corridors","Private sector attraction","Technology development","Employment generation"]},
      {t:"Bamboo Economy: Green Gold",c:"Economy & Environment",kp:["Northeast potential","Industrial applications","Carbon sequestration","Policy support needs"]},
      {t:"Healthcare Infrastructure in Tier-2 Cities",c:"Economy & Environment",kp:["Hospital density gaps","Specialist availability","Medical tourism potential","Telemedicine supplement"]},
      {t:"Wetland Conservation in India",c:"Economy & Environment",kp:["Ecosystem services value","Ramsar site management","Urban encroachment","Biodiversity protection"]},
      {t:"Value Addition in Agriculture",c:"Economy & Environment",kp:["Food processing parks","Cold chain development","Brand building for farm products","Export market access"]},
      {t:"Textile Industry Competitiveness",c:"Economy & Environment",kp:["PLI scheme impact","Technology upgradation","Sustainability compliance","Vietnam and Bangladesh competition"]},
      {t:"Mining Sector Governance",c:"Economy & Environment",kp:["Auction transparency","Environmental compliance","Community benefit sharing","Illegal mining control"]},
      {t:"Electric Mobility Ecosystem",c:"Economy & Environment",kp:["Charging infrastructure","Battery swapping","Two-wheeler electrification","Public transport conversion"]},
      {t:"National Education Mission Financing",c:"Economy & Environment",kp:["6% GDP target","Public-private investment","Research funding","International collaboration"]},
      {t:"Forest-Based Livelihoods",c:"Economy & Environment",kp:["Tribal community rights","Minor forest produce","Eco-tourism opportunities","Conservation incentives"]},
      {t:"India's Dairy Revolution 2.0",c:"Economy & Environment",kp:["Technology in dairying","Cold chain gaps","Export potential","Cooperative model scaling"]},
      {t:"Urban Flooding: Causes and Solutions",c:"Economy & Environment",kp:["Concretization impact","Drainage infrastructure","Sponge city concept","Wetland preservation"]},
      {t:"Defense Production Corridor Impact",c:"Economy & Environment",kp:["Investment attraction","MSMEs in defense","Technology clusters","Export orientation"]},
      {t:"India's Steel Industry Growth",c:"Economy & Environment",kp:["Infrastructure demand linkage","Green steel transition","Import protection","Technology modernization"]},
      {t:"Agri-Tech Startups in India",c:"Economy & Environment",kp:["Farm-to-fork platforms","Precision agriculture","Drone technology","Farmer income impact"]},
      {t:"Credit Guarantee for Small Business",c:"Economy & Environment",kp:["CGTMSE scheme","Banks' risk appetite","Collateral-free lending impact","Default management"]},
      {t:"Rainwater Harvesting: Policy and Practice",c:"Economy & Environment",kp:["State-level mandates","Traditional wisdom integration","Groundwater recharge","Urban implementation"]},
      {t:"India's Aviation Sector Growth",c:"Economy & Environment",kp:["UDAN scheme impact","Airport privatization","MRO development","Sustainability challenges"]},
      {t:"Tribal Art and Craft Economy",c:"Economy & Environment",kp:["GI tag protection","E-commerce market access","Skill preservation","Fair trade practices"]},
      {t:"River-Linking Project: Pros and Cons",c:"Economy & Environment",kp:["Water redistribution benefits","Environmental impact","Interstate disputes","Cost-benefit analysis"]},
      {t:"Corporate Social Responsibility in India",c:"Economy & Environment",kp:["Mandatory CSR spending","Impact measurement","Best practices","Rural development focus"]},
      {t:"Natural Gas Economy for India",c:"Economy & Environment",kp:["LNG import infrastructure","City gas distribution","Compressed bio-gas","Pricing reform"]},
      {t:"Honey Mission and Bee Economy",c:"Economy & Environment",kp:["Pollination services value","Income generation for farmers","Quality standards","Export potential"]}
    ];
    return topics[i];
  }),
  // Abstract (40)
  ...Array.from({length:40}, (_, i) => {
    const topics = [
      {t:"Pen is Mightier Than the Sword",c:"Abstract & Philosophical",kp:["Historical examples","Media influence","Diplomatic solutions","Literature as weapon"]},
      {t:"Unity in Diversity: India's Strength",c:"Abstract & Philosophical",kp:["Cultural plurality","Federal structure","Social cohesion challenges","National identity"]},
      {t:"Knowledge is Power",c:"Abstract & Philosophical",kp:["Information age relevance","Education as equalizer","Wisdom vs information","Power dynamics"]},
      {t:"Fortune Favors the Brave",c:"Abstract & Philosophical",kp:["Risk-taking in leadership","Military courage examples","Calculated boldness","Fear management"]},
      {t:"Actions Speak Louder Than Words",c:"Abstract & Philosophical",kp:["Leadership by example","Promise vs delivery gap","Body language importance","Consistency in behavior"]},
      {t:"The Role of Failure in Success",c:"Abstract & Philosophical",kp:["Growth mindset concept","Resilience building","Innovation through iteration","Famous failure stories"]},
      {t:"Character vs Reputation",c:"Abstract & Philosophical",kp:["Internal vs external perception","Integrity in private life","Social media persona","Long-term vs short-term"]},
      {t:"Is Money the Root of All Evil?",c:"Abstract & Philosophical",kp:["Wealth creation benefits","Corruption and greed","Philanthropy examples","Material vs spiritual"]},
      {t:"Leadership in Times of Crisis",c:"Abstract & Philosophical",kp:["Decision-making under pressure","Communication importance","Empathy and firmness","Historical crisis leaders"]},
      {t:"Simplicity as a Way of Life",c:"Abstract & Philosophical",kp:["Gandhian simplicity","Minimalism movement","Environmental benefits","Mental clarity"]},
      {t:"Blood is Thicker Than Water",c:"Abstract & Philosophical",kp:["Family bonds importance","Chosen family concept","Military brotherhood","Conflicting loyalties"]},
      {t:"Time and Tide Wait for None",c:"Abstract & Philosophical",kp:["Time management","Seizing opportunities","Procrastination dangers","Legacy building"]},
      {t:"Where There is a Will There is a Way",c:"Abstract & Philosophical",kp:["Determination stories","Obstacle overcoming","Mental strength","Goal setting"]},
      {t:"Is Discipline More Important Than Talent?",c:"Abstract & Philosophical",kp:["10,000 hour rule","Military discipline culture","Natural ability limits","Consistency as skill"]},
      {t:"Service Before Self",c:"Abstract & Philosophical",kp:["Military ethos","Public service motivation","Sacrifice and duty","Selfless leadership examples"]},
      {t:"The Best Defense is a Good Offense",c:"Abstract & Philosophical",kp:["Proactive vs reactive","Military strategy debate","Business competition","Personal growth application"]},
      {t:"All That Glitters is Not Gold",c:"Abstract & Philosophical",kp:["Surface vs substance","Social media deception","Critical thinking importance","True value assessment"]},
      {t:"Hope: Last Resort or First Strategy?",c:"Abstract & Philosophical",kp:["Optimism in adversity","Strategic hope vs naive hope","Prisoner of war survival","Building morale"]},
      {t:"Gratitude as a Life Philosophy",c:"Abstract & Philosophical",kp:["Psychological benefits","Relationship strengthening","Professional success link","Cultural expressions"]},
      {t:"Solitude vs Loneliness",c:"Abstract & Philosophical",kp:["Creative benefits of solitude","Leadership introspection","Military isolation handling","Self-awareness development"]},
      {t:"Art of Listening",c:"Abstract & Philosophical",kp:["Active listening techniques","Intelligence gathering","Empathetic leadership","Conflict resolution"]},
      {t:"Integrity: The Foundation of Trust",c:"Abstract & Philosophical",kp:["Institutional trust erosion","Personal integrity tests","Military honor code","Whistleblower dilemmas"]},
      {t:"Adaptability: Darwin's Lesson for Leaders",c:"Abstract & Philosophical",kp:["Survival of fittest adaptation","Military flexibility","Business pivot examples","Personal growth mindset"]},
      {t:"Courage of Conviction",c:"Abstract & Philosophical",kp:["Standing against majority","Moral courage vs physical","Decision ownership","Historical examples"]},
      {t:"Empathy in Leadership",c:"Abstract & Philosophical",kp:["Understanding subordinates","Mission vs welfare balance","Emotional intelligence","Building team loyalty"]},
      {t:"Patience: A Forgotten Virtue",c:"Abstract & Philosophical",kp:["Strategic patience in warfare","Instant gratification culture","Long-term planning","Perseverance stories"]},
      {t:"Excellence vs Perfection",c:"Abstract & Philosophical",kp:["Continuous improvement","Analysis paralysis","Good enough principle","Quality commitment"]},
      {t:"Wisdom of Crowds vs Expert Opinion",c:"Abstract & Philosophical",kp:["Democratic decision-making","Group think dangers","Specialist knowledge value","Balanced approach"]},
      {t:"Does History Repeat Itself?",c:"Abstract & Philosophical",kp:["Pattern recognition","Learning from past","Contextual differences","Predictive value"]},
      {t:"Mind Over Matter",c:"Abstract & Philosophical",kp:["Mental strength training","Physical endurance link","Meditation and focus","Military mental conditioning"]},
      {t:"Legacy: What Will You Leave Behind?",c:"Abstract & Philosophical",kp:["Purpose-driven life","Impact measurement","Institutional vs personal legacy","Generational responsibility"]},
      {t:"Humor as Leadership Tool",c:"Abstract & Philosophical",kp:["Morale building","Stress relief","Cultural sensitivity","Appropriate timing"]},
      {t:"Responsibility vs Authority",c:"Abstract & Philosophical",kp:["Accountability without power","Delegation principles","Mission command concept","Empowerment culture"]},
      {t:"Is History Written by Winners?",c:"Abstract & Philosophical",kp:["Historiography bias","Alternative narratives","Post-colonial perspectives","Truth and reconciliation"]},
      {t:"Silence as Communication",c:"Abstract & Philosophical",kp:["Strategic silence","Active listening","Meditation practice","Diplomatic signaling"]},
      {t:"Innovation vs Tradition in Armed Forces",c:"Abstract & Philosophical",kp:["Doctrinal evolution","Technology adoption resistance","Core values preservation","Generational change"]},
      {t:"Self-Discipline: The Master Key",c:"Abstract & Philosophical",kp:["Habit formation science","Military regiment life","Goal achievement","Freedom through discipline"]},
      {t:"Are Leaders Born or Made?",c:"Abstract & Philosophical",kp:["Nature vs nurture","Military leadership training","Trait vs situational theory","Developmental experiences"]},
      {t:"Value of Sacrifice in Modern World",c:"Abstract & Philosophical",kp:["Military sacrifice culture","Personal sacrifices for goals","Societal expectations","Recognition and remembrance"]},
      {t:"Trust: The Currency of Leadership",c:"Abstract & Philosophical",kp:["Building trust mechanisms","Rebuilding broken trust","Institutional trust crisis","Leading with vulnerability"]}
    ];
    return topics[i];
  })
];

// Build Lecturette sets (4 topics each)
const difficultyMap = (i) => i < 20 ? "Easy" : i < 40 ? "Medium" : "Hard";
const lecResult = {
  metadata: { total_topics: 240, total_sets: 60, speech_duration_minutes: 3, prep_time_seconds: 180, version: "2.0" },
  sets: []
};

for (let i = 0; i < 60; i++) {
  lecResult.sets.push({
    set_id: i + 1,
    name: `Set ${String(i + 1).padStart(2, '0')}`,
    topics: [0,1,2,3].map(j => {
      const topicIdx = i * 4 + j;
      const t = lecturetteTopicBank[topicIdx % lecturetteTopicBank.length];
      return {
        topic: t.t,
        category: t.c,
        key_points: t.kp,
        difficulty: difficultyMap(i)
      };
    })
  });
}

fs.writeFileSync('src/data/lecturette_60_sets.json', JSON.stringify(lecResult, null, 2));
console.log('Lecturette: Generated ' + lecResult.sets.length + ' sets with ' + (lecResult.sets.length * 4) + ' topics');
