-- 1. EXAMS TABLE
CREATE TABLE study_exams (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    color TEXT DEFAULT 'emerald',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. SUBJECTS TABLE
CREATE TABLE study_subjects (
    id TEXT PRIMARY KEY,
    exam_id TEXT NOT NULL REFERENCES study_exams(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    icon TEXT DEFAULT 'book',
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. CHAPTERS TABLE
CREATE TABLE study_chapters (
    id TEXT PRIMARY KEY,
    subject_id TEXT NOT NULL REFERENCES study_subjects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    estimated_time TEXT,
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TOPICS TABLE (The core content generated by AI)
CREATE TABLE study_topics (
    id TEXT PRIMARY KEY,
    chapter_id TEXT NOT NULL REFERENCES study_chapters(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    type TEXT DEFAULT 'Theory',
    read_time TEXT,
    content TEXT NOT NULL,
    key_takeaways JSONB, -- Array of strings
    quick_quiz JSONB, -- Object with question, options array, answer, explanation
    youtube_url TEXT, -- Added per user request to link videos directly to topics
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. RESOURCES VAULT (PDFs & Extra Videos)
CREATE TABLE study_resources (
    id TEXT PRIMARY KEY,
    exam_id TEXT NOT NULL REFERENCES study_exams(id) ON DELETE CASCADE,
    resource_type TEXT NOT NULL, -- 'pdf' or 'video'
    title TEXT NOT NULL,
    description TEXT,
    url TEXT, -- Link to PDF file or YouTube Video ID
    metadata JSONB, -- For PDF pages or Video instructor/duration info
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- SETUP RLS (Row Level Security) - Allow public read access to study material
ALTER TABLE study_exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_resources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on exams" ON study_exams FOR SELECT USING (true);
CREATE POLICY "Allow public read access on subjects" ON study_subjects FOR SELECT USING (true);
CREATE POLICY "Allow public read access on chapters" ON study_chapters FOR SELECT USING (true);
CREATE POLICY "Allow public read access on topics" ON study_topics FOR SELECT USING (true);
CREATE POLICY "Allow public read access on resources" ON study_resources FOR SELECT USING (true);

-- Indexes for performance
CREATE INDEX idx_subjects_exam ON study_subjects(exam_id);
CREATE INDEX idx_chapters_subject ON study_chapters(subject_id);
CREATE INDEX idx_topics_chapter ON study_topics(chapter_id);
CREATE INDEX idx_resources_exam ON study_resources(exam_id);

-- SEED DATA (Initial exams)
INSERT INTO study_exams (id, title, category, description, color) VALUES 
('nda', 'NDA Exam Study Portal', 'NDA (National Defence Academy)', 'Premium preparation archives for the National Defence Academy entry. Mapped strictly to the official UPSC NDA syllabus parameters.', 'emerald'),
('cds', 'CDS Exam Study Portal', 'CDS (Combined Defence Services)', 'Advanced training resources for the Combined Defence Services entry. Curated for IMA, OTA, INA, and AFA aspirants.', 'amber'),
('afcat', 'AFCAT Exam Study Portal', 'AFCAT (Air Force Common Admission Test)', 'Specialized Air Force preparation. Focused on military aptitude, spatial reasoning, and aviation terminology.', 'blue'),
('ssb', 'SSB Interview Master Guide', 'SSB (Services Selection Board)', 'Comprehensive psychological, GTO, and interview master templates. Standardized against DRDO DIPR guidelines for 15 OLQs.', 'red');

-- 6. PIQ SUBMISSIONS
CREATE TABLE piq_submissions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    personal_details JSONB,
    education_details JSONB,
    hobbies_sports JSONB,
    ssb_history JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Secure the table so users can only access their own data
ALTER TABLE piq_submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert their own piq" ON piq_submissions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can select their own piq" ON piq_submissions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own piq" ON piq_submissions FOR UPDATE USING (auth.uid() = user_id);

-- Optional: Create index for faster querying by user_id
CREATE INDEX idx_piq_user_id ON piq_submissions(user_id);
