import { TopicContent } from '../../types'

export const CDS_GK_HISTORY_AUTOGEN: TopicContent[] = [
  {
    id: 'cds-hist-viceroys',
    title: 'Viceroy Reforms & Key Acts',
    readTimeMinutes: 16,
    content: [
      { type: 'heading', data: 'Viceroy Reforms & Key Acts Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Viceroy Reforms & Key Acts. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Viceroy Reforms & Key Acts',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Viceroy Reforms & Key Acts',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Viceroy Reforms & Key Acts?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-hist-science',
    title: 'General Science: Cell Biology & Systems',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'General Science: Cell Biology & Systems Overview' },
      { type: 'text', data: 'This is the autogenerated study material for General Science: Cell Biology & Systems. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of General Science: Cell Biology & Systems',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of General Science: Cell Biology & Systems',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying General Science: Cell Biology & Systems?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-ai-01',
    title: 'Indian National Movement - 1857 to 1947',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Indian National Movement - 1857 to 1947 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Indian National Movement - 1857 to 1947. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Indian National Movement - 1857 to 1947',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Indian National Movement - 1857 to 1947',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Indian National Movement - 1857 to 1947?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-ai-02',
    title: 'Mahatma Gandhi and Civil Disobedience Movement',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Mahatma Gandhi and Civil Disobedience Movement Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Mahatma Gandhi and Civil Disobedience Movement. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Mahatma Gandhi and Civil Disobedience Movement',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Mahatma Gandhi and Civil Disobedience Movement',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Mahatma Gandhi and Civil Disobedience Movement?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-ai-03',
    title: 'Quit India Movement and Independence',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Quit India Movement and Independence Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Quit India Movement and Independence. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Quit India Movement and Independence',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Quit India Movement and Independence',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Quit India Movement and Independence?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-ai-04',
    title: 'Post-Independence India - Integration of States',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Post-Independence India - Integration of States Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Post-Independence India - Integration of States. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Post-Independence India - Integration of States',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Post-Independence India - Integration of States',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Post-Independence India - Integration of States?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-ai-05',
    title: 'World Wars and Their Impact on India',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'World Wars and Their Impact on India Overview' },
      { type: 'text', data: 'This is the autogenerated study material for World Wars and Their Impact on India. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of World Wars and Their Impact on India',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of World Wars and Their Impact on India',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying World Wars and Their Impact on India?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-ai-06',
    title: 'Ancient India - Indus Valley to Gupta Empire',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Ancient India - Indus Valley to Gupta Empire Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Ancient India - Indus Valley to Gupta Empire. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Ancient India - Indus Valley to Gupta Empire',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Ancient India - Indus Valley to Gupta Empire',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Ancient India - Indus Valley to Gupta Empire?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-ai-07',
    title: 'Medieval India - Delhi Sultanate and Mughal Empire',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Medieval India - Delhi Sultanate and Mughal Empire Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Medieval India - Delhi Sultanate and Mughal Empire. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Medieval India - Delhi Sultanate and Mughal Empire',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Medieval India - Delhi Sultanate and Mughal Empire',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Medieval India - Delhi Sultanate and Mughal Empire?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-27',
    title: 'Modern Indian History - Advanced Topic 27',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 27 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 27. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 27',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 27',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 27?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-30',
    title: 'Modern Indian History - Advanced Topic 30',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 30 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 30. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 30',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 30',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 30?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-33',
    title: 'Modern Indian History - Advanced Topic 33',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 33 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 33. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 33',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 33',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 33?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-36',
    title: 'Modern Indian History - Advanced Topic 36',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 36 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 36. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 36',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 36',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 36?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-39',
    title: 'Modern Indian History - Advanced Topic 39',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 39 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 39. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 39',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 39',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 39?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-42',
    title: 'Modern Indian History - Advanced Topic 42',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 42 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 42. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 42',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 42',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 42?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-45',
    title: 'Modern Indian History - Advanced Topic 45',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 45 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 45. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 45',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 45',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 45?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-48',
    title: 'Modern Indian History - Advanced Topic 48',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 48 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 48. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 48',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 48',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 48?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-51',
    title: 'Modern Indian History - Advanced Topic 51',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 51 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 51. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 51',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 51',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 51?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-54',
    title: 'Modern Indian History - Advanced Topic 54',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 54 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 54. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 54',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 54',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 54?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-57',
    title: 'Modern Indian History - Advanced Topic 57',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 57 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 57. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 57',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 57',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 57?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-60',
    title: 'Modern Indian History - Advanced Topic 60',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 60 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 60. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 60',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 60',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 60?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-63',
    title: 'Modern Indian History - Advanced Topic 63',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 63 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 63. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 63',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 63',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 63?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-66',
    title: 'Modern Indian History - Advanced Topic 66',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 66 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 66. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 66',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 66',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 66?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-67',
    title: 'Modern Indian History - Advanced Topic 67',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 67 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 67. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 67',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 67',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 67?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-69',
    title: 'Modern Indian History - Advanced Topic 69',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 69 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 69. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 69',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 69',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 69?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-71',
    title: 'Modern Indian History - Advanced Topic 71',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 71 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 71. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 71',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 71',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 71?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-72',
    title: 'Modern Indian History - Advanced Topic 72',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 72 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 72. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 72',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 72',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 72?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-73',
    title: 'Modern Indian History - Advanced Topic 73',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 73 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 73. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 73',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 73',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 73?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-75',
    title: 'Modern Indian History - Advanced Topic 75',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 75 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 75. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 75',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 75',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 75?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-77',
    title: 'Modern Indian History - Advanced Topic 77',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 77 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 77. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 77',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 77',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 77?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-78',
    title: 'Modern Indian History - Advanced Topic 78',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 78 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 78. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 78',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 78',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 78?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-79',
    title: 'Modern Indian History - Advanced Topic 79',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 79 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 79. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 79',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 79',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 79?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-81',
    title: 'Modern Indian History - Advanced Topic 81',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 81 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 81. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 81',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 81',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 81?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-83',
    title: 'Modern Indian History - Advanced Topic 83',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 83 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 83. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 83',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 83',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 83?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-84',
    title: 'Modern Indian History - Advanced Topic 84',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 84 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 84. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 84',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 84',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 84?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-85',
    title: 'Modern Indian History - Advanced Topic 85',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 85 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 85. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 85',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 85',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 85?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-87',
    title: 'Modern Indian History - Advanced Topic 87',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 87 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 87. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 87',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 87',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 87?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-89',
    title: 'Modern Indian History - Advanced Topic 89',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 89 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 89. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 89',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 89',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 89?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-90',
    title: 'Modern Indian History - Advanced Topic 90',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 90 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 90. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 90',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 90',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 90?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-91',
    title: 'Modern Indian History - Advanced Topic 91',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 91 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 91. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 91',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 91',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 91?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-93',
    title: 'Modern Indian History - Advanced Topic 93',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 93 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 93. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 93',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 93',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 93?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-95',
    title: 'Modern Indian History - Advanced Topic 95',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 95 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 95. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 95',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 95',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 95?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-96',
    title: 'Modern Indian History - Advanced Topic 96',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 96 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 96. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 96',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 96',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 96?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-97',
    title: 'Modern Indian History - Advanced Topic 97',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 97 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 97. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 97',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 97',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 97?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-history-bulk-99',
    title: 'Modern Indian History - Advanced Topic 99',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Modern Indian History - Advanced Topic 99 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Modern Indian History - Advanced Topic 99. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Modern Indian History - Advanced Topic 99',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Modern Indian History - Advanced Topic 99',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Modern Indian History - Advanced Topic 99?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
]
