import { TopicContent } from '../../types'

export const CDS_GK_MATH_AUTOGEN: TopicContent[] = [
  {
    id: 'cds-math-mensuration',
    title: '3D Geometry & Mensuration',
    readTimeMinutes: 14,
    content: [
      { type: 'heading', data: '3D Geometry & Mensuration Overview' },
      { type: 'text', data: 'This is the autogenerated study material for 3D Geometry & Mensuration. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of 3D Geometry & Mensuration',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of 3D Geometry & Mensuration',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying 3D Geometry & Mensuration?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-ai-01',
    title: 'Number System - HCF, LCM, Prime Numbers',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Number System - HCF, LCM, Prime Numbers Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Number System - HCF, LCM, Prime Numbers. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Number System - HCF, LCM, Prime Numbers',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Number System - HCF, LCM, Prime Numbers',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Number System - HCF, LCM, Prime Numbers?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-ai-02',
    title: 'Percentage, Profit and Loss - Shortcuts',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Percentage, Profit and Loss - Shortcuts Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Percentage, Profit and Loss - Shortcuts. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Percentage, Profit and Loss - Shortcuts',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Percentage, Profit and Loss - Shortcuts',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Percentage, Profit and Loss - Shortcuts?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-ai-03',
    title: 'Simple and Compound Interest - Formulas and Tricks',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Simple and Compound Interest - Formulas and Tricks Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Simple and Compound Interest - Formulas and Tricks. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Simple and Compound Interest - Formulas and Tricks',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Simple and Compound Interest - Formulas and Tricks',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Simple and Compound Interest - Formulas and Tricks?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-ai-04',
    title: 'Ratio and Proportion - Concepts and Problems',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Ratio and Proportion - Concepts and Problems Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Ratio and Proportion - Concepts and Problems. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Ratio and Proportion - Concepts and Problems',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Ratio and Proportion - Concepts and Problems',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Ratio and Proportion - Concepts and Problems?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-ai-05',
    title: 'Time and Work - Pipes and Cisterns',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Time and Work - Pipes and Cisterns Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Time and Work - Pipes and Cisterns. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Time and Work - Pipes and Cisterns',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Time and Work - Pipes and Cisterns',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Time and Work - Pipes and Cisterns?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-ai-06',
    title: 'Geometry - Triangles, Circles, Quadrilaterals',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Geometry - Triangles, Circles, Quadrilaterals Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Geometry - Triangles, Circles, Quadrilaterals. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Geometry - Triangles, Circles, Quadrilaterals',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Geometry - Triangles, Circles, Quadrilaterals',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Geometry - Triangles, Circles, Quadrilaterals?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-ai-07',
    title: 'Trigonometry - Heights and Distances',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Trigonometry - Heights and Distances Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Trigonometry - Heights and Distances. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Trigonometry - Heights and Distances',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Trigonometry - Heights and Distances',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Trigonometry - Heights and Distances?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-28',
    title: 'Elementary Mathematics - Advanced Topic 28',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 28 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 28. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 28',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 28',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 28?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-31',
    title: 'Elementary Mathematics - Advanced Topic 31',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 31 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 31. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 31',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 31',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 31?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-34',
    title: 'Elementary Mathematics - Advanced Topic 34',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 34 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 34. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 34',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 34',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 34?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-37',
    title: 'Elementary Mathematics - Advanced Topic 37',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 37 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 37. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 37',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 37',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 37?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-40',
    title: 'Elementary Mathematics - Advanced Topic 40',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 40 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 40. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 40',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 40',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 40?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-43',
    title: 'Elementary Mathematics - Advanced Topic 43',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 43 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 43. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 43',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 43',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 43?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-46',
    title: 'Elementary Mathematics - Advanced Topic 46',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 46 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 46. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 46',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 46',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 46?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-49',
    title: 'Elementary Mathematics - Advanced Topic 49',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 49 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 49. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 49',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 49',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 49?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-52',
    title: 'Elementary Mathematics - Advanced Topic 52',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 52 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 52. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 52',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 52',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 52?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-55',
    title: 'Elementary Mathematics - Advanced Topic 55',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 55 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 55. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 55',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 55',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 55?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-58',
    title: 'Elementary Mathematics - Advanced Topic 58',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 58 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 58. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 58',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 58',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 58?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-61',
    title: 'Elementary Mathematics - Advanced Topic 61',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 61 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 61. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 61',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 61',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 61?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-64',
    title: 'Elementary Mathematics - Advanced Topic 64',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 64 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 64. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 64',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 64',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 64?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-67',
    title: 'Elementary Mathematics - Advanced Topic 67',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 67 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 67. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 67',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 67',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 67?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-68',
    title: 'Elementary Mathematics - Advanced Topic 68',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 68 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 68. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 68',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 68',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 68?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-70',
    title: 'Elementary Mathematics - Advanced Topic 70',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 70 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 70. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 70',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 70',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 70?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-72',
    title: 'Elementary Mathematics - Advanced Topic 72',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 72 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 72. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 72',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 72',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 72?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-73',
    title: 'Elementary Mathematics - Advanced Topic 73',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 73 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 73. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 73',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 73',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 73?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-74',
    title: 'Elementary Mathematics - Advanced Topic 74',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 74 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 74. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 74',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 74',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 74?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-76',
    title: 'Elementary Mathematics - Advanced Topic 76',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 76 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 76. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 76',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 76',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 76?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-78',
    title: 'Elementary Mathematics - Advanced Topic 78',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 78 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 78. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 78',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 78',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 78?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-79',
    title: 'Elementary Mathematics - Advanced Topic 79',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 79 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 79. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 79',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 79',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 79?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-80',
    title: 'Elementary Mathematics - Advanced Topic 80',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 80 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 80. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 80',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 80',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 80?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-82',
    title: 'Elementary Mathematics - Advanced Topic 82',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 82 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 82. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 82',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 82',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 82?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-84',
    title: 'Elementary Mathematics - Advanced Topic 84',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 84 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 84. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 84',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 84',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 84?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-85',
    title: 'Elementary Mathematics - Advanced Topic 85',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 85 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 85. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 85',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 85',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 85?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-86',
    title: 'Elementary Mathematics - Advanced Topic 86',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 86 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 86. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 86',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 86',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 86?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-88',
    title: 'Elementary Mathematics - Advanced Topic 88',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 88 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 88. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 88',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 88',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 88?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-90',
    title: 'Elementary Mathematics - Advanced Topic 90',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 90 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 90. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 90',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 90',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 90?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-91',
    title: 'Elementary Mathematics - Advanced Topic 91',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 91 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 91. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 91',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 91',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 91?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-92',
    title: 'Elementary Mathematics - Advanced Topic 92',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 92 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 92. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 92',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 92',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 92?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-94',
    title: 'Elementary Mathematics - Advanced Topic 94',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 94 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 94. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 94',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 94',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 94?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-96',
    title: 'Elementary Mathematics - Advanced Topic 96',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 96 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 96. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 96',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 96',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 96?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-97',
    title: 'Elementary Mathematics - Advanced Topic 97',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 97 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 97. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 97',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 97',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 97?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'cds-gk-math-bulk-98',
    title: 'Elementary Mathematics - Advanced Topic 98',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'Elementary Mathematics - Advanced Topic 98 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Elementary Mathematics - Advanced Topic 98. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Elementary Mathematics - Advanced Topic 98',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Elementary Mathematics - Advanced Topic 98',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Elementary Mathematics - Advanced Topic 98?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
]
