import { TopicContent } from '../../types'

export const SSB_TAT_AUTOGEN: TopicContent[] = [
  {
    id: 'ssb-tat-heroes',
    title: 'TAT: Hero Selection & Themes',
    readTimeMinutes: 15,
    content: [
      { type: 'heading', data: 'TAT: Hero Selection & Themes Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT: Hero Selection & Themes. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT: Hero Selection & Themes',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT: Hero Selection & Themes',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT: Hero Selection & Themes?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-wat-craft',
    title: 'WAT: Sentence Crafting',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'WAT: Sentence Crafting Overview' },
      { type: 'text', data: 'This is the autogenerated study material for WAT: Sentence Crafting. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of WAT: Sentence Crafting',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of WAT: Sentence Crafting',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying WAT: Sentence Crafting?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-ai-01',
    title: 'TAT - Thematic Apperception Test Complete Guide',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'TAT - Thematic Apperception Test Complete Guide Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT - Thematic Apperception Test Complete Guide. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT - Thematic Apperception Test Complete Guide',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT - Thematic Apperception Test Complete Guide',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT - Thematic Apperception Test Complete Guide?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-ai-02',
    title: 'How to Write TAT Stories - Structure and OLQs',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'How to Write TAT Stories - Structure and OLQs Overview' },
      { type: 'text', data: 'This is the autogenerated study material for How to Write TAT Stories - Structure and OLQs. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of How to Write TAT Stories - Structure and OLQs',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of How to Write TAT Stories - Structure and OLQs',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying How to Write TAT Stories - Structure and OLQs?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-ai-03',
    title: 'WAT - Word Association Test Strategy',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'WAT - Word Association Test Strategy Overview' },
      { type: 'text', data: 'This is the autogenerated study material for WAT - Word Association Test Strategy. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of WAT - Word Association Test Strategy',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of WAT - Word Association Test Strategy',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying WAT - Word Association Test Strategy?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-ai-04',
    title: 'WAT - 60 Practice Words with Model Responses',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'WAT - 60 Practice Words with Model Responses Overview' },
      { type: 'text', data: 'This is the autogenerated study material for WAT - 60 Practice Words with Model Responses. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of WAT - 60 Practice Words with Model Responses',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of WAT - 60 Practice Words with Model Responses',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying WAT - 60 Practice Words with Model Responses?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-ai-05',
    title: 'Psychology Tests - What Assessors Look For',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Psychology Tests - What Assessors Look For Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Psychology Tests - What Assessors Look For. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Psychology Tests - What Assessors Look For',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Psychology Tests - What Assessors Look For',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Psychology Tests - What Assessors Look For?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-39',
    title: 'TAT & WAT - Advanced Topic 39',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 39 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 39. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 39',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 39',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 39?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-40',
    title: 'TAT & WAT - Advanced Topic 40',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 40 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 40. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 40',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 40',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 40?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-42',
    title: 'TAT & WAT - Advanced Topic 42',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 42 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 42. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 42',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 42',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 42?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-44',
    title: 'TAT & WAT - Advanced Topic 44',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 44 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 44. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 44',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 44',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 44?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-46',
    title: 'TAT & WAT - Advanced Topic 46',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 46 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 46. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 46',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 46',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 46?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-48',
    title: 'TAT & WAT - Advanced Topic 48',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 48 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 48. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 48',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 48',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 48?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-49',
    title: 'TAT & WAT - Advanced Topic 49',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 49 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 49. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 49',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 49',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 49?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-50',
    title: 'TAT & WAT - Advanced Topic 50',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 50 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 50. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 50',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 50',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 50?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-52',
    title: 'TAT & WAT - Advanced Topic 52',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 52 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 52. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 52',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 52',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 52?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-54',
    title: 'TAT & WAT - Advanced Topic 54',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 54 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 54. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 54',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 54',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 54?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-56',
    title: 'TAT & WAT - Advanced Topic 56',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 56 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 56. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 56',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 56',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 56?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-58',
    title: 'TAT & WAT - Advanced Topic 58',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 58 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 58. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 58',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 58',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 58?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-59',
    title: 'TAT & WAT - Advanced Topic 59',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 59 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 59. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 59',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 59',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 59?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-60',
    title: 'TAT & WAT - Advanced Topic 60',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 60 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 60. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 60',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 60',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 60?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-62',
    title: 'TAT & WAT - Advanced Topic 62',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 62 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 62. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 62',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 62',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 62?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-64',
    title: 'TAT & WAT - Advanced Topic 64',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 64 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 64. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 64',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 64',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 64?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-66',
    title: 'TAT & WAT - Advanced Topic 66',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 66 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 66. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 66',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 66',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 66?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-68',
    title: 'TAT & WAT - Advanced Topic 68',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 68 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 68. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 68',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 68',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 68?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-69',
    title: 'TAT & WAT - Advanced Topic 69',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 69 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 69. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 69',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 69',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 69?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-70',
    title: 'TAT & WAT - Advanced Topic 70',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 70 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 70. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 70',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 70',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 70?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-72',
    title: 'TAT & WAT - Advanced Topic 72',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 72 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 72. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 72',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 72',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 72?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-74',
    title: 'TAT & WAT - Advanced Topic 74',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 74 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 74. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 74',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 74',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 74?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-76',
    title: 'TAT & WAT - Advanced Topic 76',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 76 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 76. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 76',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 76',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 76?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-78',
    title: 'TAT & WAT - Advanced Topic 78',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 78 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 78. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 78',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 78',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 78?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-79',
    title: 'TAT & WAT - Advanced Topic 79',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 79 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 79. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 79',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 79',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 79?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-80',
    title: 'TAT & WAT - Advanced Topic 80',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 80 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 80. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 80',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 80',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 80?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-82',
    title: 'TAT & WAT - Advanced Topic 82',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 82 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 82. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 82',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 82',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 82?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-84',
    title: 'TAT & WAT - Advanced Topic 84',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 84 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 84. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 84',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 84',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 84?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-86',
    title: 'TAT & WAT - Advanced Topic 86',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 86 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 86. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 86',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 86',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 86?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-88',
    title: 'TAT & WAT - Advanced Topic 88',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 88 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 88. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 88',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 88',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 88?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-89',
    title: 'TAT & WAT - Advanced Topic 89',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 89 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 89. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 89',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 89',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 89?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-90',
    title: 'TAT & WAT - Advanced Topic 90',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 90 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 90. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 90',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 90',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 90?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-92',
    title: 'TAT & WAT - Advanced Topic 92',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 92 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 92. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 92',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 92',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 92?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-94',
    title: 'TAT & WAT - Advanced Topic 94',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 94 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 94. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 94',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 94',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 94?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-96',
    title: 'TAT & WAT - Advanced Topic 96',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 96 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 96. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 96',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 96',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 96?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-98',
    title: 'TAT & WAT - Advanced Topic 98',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 98 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 98. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 98',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 98',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 98?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-tat-bulk-99',
    title: 'TAT & WAT - Advanced Topic 99',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'TAT & WAT - Advanced Topic 99 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for TAT & WAT - Advanced Topic 99. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of TAT & WAT - Advanced Topic 99',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of TAT & WAT - Advanced Topic 99',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying TAT & WAT - Advanced Topic 99?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
]
