import { TopicContent } from '../../types'

export const SSB_SRT_AUTOGEN: TopicContent[] = [
  {
    id: 'ssb-srt-strategy',
    title: 'SRT: Practical Response Framework',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT: Practical Response Framework Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT: Practical Response Framework. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT: Practical Response Framework',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT: Practical Response Framework',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT: Practical Response Framework?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-sd-guide',
    title: 'Self Description: Perspectives',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Self Description: Perspectives Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Self Description: Perspectives. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Self Description: Perspectives',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Self Description: Perspectives',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Self Description: Perspectives?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-ai-01',
    title: 'SRT - Situation Reaction Test Complete Guide',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'SRT - Situation Reaction Test Complete Guide Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT - Situation Reaction Test Complete Guide. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT - Situation Reaction Test Complete Guide',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT - Situation Reaction Test Complete Guide',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT - Situation Reaction Test Complete Guide?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-ai-02',
    title: 'SRT - 30 Practice Situations with Model Answers',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'SRT - 30 Practice Situations with Model Answers Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT - 30 Practice Situations with Model Answers. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT - 30 Practice Situations with Model Answers',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT - 30 Practice Situations with Model Answers',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT - 30 Practice Situations with Model Answers?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-ai-03',
    title: 'Self Description Test - How to Write Effectively',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Self Description Test - How to Write Effectively Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Self Description Test - How to Write Effectively. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Self Description Test - How to Write Effectively',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Self Description Test - How to Write Effectively',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Self Description Test - How to Write Effectively?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-ai-04',
    title: 'Self Description - Parents, Teachers, Friends Perspective',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Self Description - Parents, Teachers, Friends Perspective Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Self Description - Parents, Teachers, Friends Perspective. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Self Description - Parents, Teachers, Friends Perspective',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Self Description - Parents, Teachers, Friends Perspective',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Self Description - Parents, Teachers, Friends Perspective?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-ai-05',
    title: 'Officer Like Qualities (OLQs) - The 15 Qualities Explained',
    readTimeMinutes: 10,
    content: [
      { type: 'heading', data: 'Officer Like Qualities (OLQs) - The 15 Qualities Explained Overview' },
      { type: 'text', data: 'This is the autogenerated study material for Officer Like Qualities (OLQs) - The 15 Qualities Explained. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of Officer Like Qualities (OLQs) - The 15 Qualities Explained',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of Officer Like Qualities (OLQs) - The 15 Qualities Explained',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying Officer Like Qualities (OLQs) - The 15 Qualities Explained?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-40',
    title: 'SRT & Self Description - Advanced Topic 40',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 40 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 40. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 40',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 40',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 40?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-41',
    title: 'SRT & Self Description - Advanced Topic 41',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 41 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 41. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 41',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 41',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 41?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-43',
    title: 'SRT & Self Description - Advanced Topic 43',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 43 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 43. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 43',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 43',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 43?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-45',
    title: 'SRT & Self Description - Advanced Topic 45',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 45 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 45. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 45',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 45',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 45?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-47',
    title: 'SRT & Self Description - Advanced Topic 47',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 47 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 47. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 47',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 47',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 47?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-49',
    title: 'SRT & Self Description - Advanced Topic 49',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 49 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 49. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 49',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 49',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 49?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-50',
    title: 'SRT & Self Description - Advanced Topic 50',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 50 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 50. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 50',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 50',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 50?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-51',
    title: 'SRT & Self Description - Advanced Topic 51',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 51 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 51. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 51',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 51',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 51?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-53',
    title: 'SRT & Self Description - Advanced Topic 53',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 53 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 53. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 53',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 53',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 53?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-55',
    title: 'SRT & Self Description - Advanced Topic 55',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 55 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 55. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 55',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 55',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 55?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-57',
    title: 'SRT & Self Description - Advanced Topic 57',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 57 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 57. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 57',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 57',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 57?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-59',
    title: 'SRT & Self Description - Advanced Topic 59',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 59 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 59. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 59',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 59',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 59?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-60',
    title: 'SRT & Self Description - Advanced Topic 60',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 60 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 60. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 60',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 60',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 60?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-61',
    title: 'SRT & Self Description - Advanced Topic 61',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 61 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 61. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 61',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 61',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 61?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-63',
    title: 'SRT & Self Description - Advanced Topic 63',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 63 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 63. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 63',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 63',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 63?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-65',
    title: 'SRT & Self Description - Advanced Topic 65',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 65 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 65. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 65',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 65',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 65?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-67',
    title: 'SRT & Self Description - Advanced Topic 67',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 67 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 67. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 67',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 67',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 67?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-69',
    title: 'SRT & Self Description - Advanced Topic 69',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 69 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 69. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 69',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 69',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 69?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-70',
    title: 'SRT & Self Description - Advanced Topic 70',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 70 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 70. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 70',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 70',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 70?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-71',
    title: 'SRT & Self Description - Advanced Topic 71',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 71 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 71. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 71',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 71',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 71?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-73',
    title: 'SRT & Self Description - Advanced Topic 73',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 73 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 73. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 73',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 73',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 73?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-75',
    title: 'SRT & Self Description - Advanced Topic 75',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 75 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 75. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 75',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 75',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 75?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-77',
    title: 'SRT & Self Description - Advanced Topic 77',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 77 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 77. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 77',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 77',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 77?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-79',
    title: 'SRT & Self Description - Advanced Topic 79',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 79 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 79. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 79',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 79',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 79?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-80',
    title: 'SRT & Self Description - Advanced Topic 80',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 80 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 80. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 80',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 80',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 80?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-81',
    title: 'SRT & Self Description - Advanced Topic 81',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 81 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 81. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 81',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 81',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 81?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-83',
    title: 'SRT & Self Description - Advanced Topic 83',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 83 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 83. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 83',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 83',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 83?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-85',
    title: 'SRT & Self Description - Advanced Topic 85',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 85 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 85. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 85',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 85',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 85?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-87',
    title: 'SRT & Self Description - Advanced Topic 87',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 87 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 87. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 87',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 87',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 87?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-89',
    title: 'SRT & Self Description - Advanced Topic 89',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 89 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 89. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 89',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 89',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 89?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-90',
    title: 'SRT & Self Description - Advanced Topic 90',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 90 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 90. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 90',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 90',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 90?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-91',
    title: 'SRT & Self Description - Advanced Topic 91',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 91 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 91. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 91',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 91',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 91?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-93',
    title: 'SRT & Self Description - Advanced Topic 93',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 93 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 93. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 93',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 93',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 93?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-95',
    title: 'SRT & Self Description - Advanced Topic 95',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 95 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 95. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 95',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 95',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 95?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-97',
    title: 'SRT & Self Description - Advanced Topic 97',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 97 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 97. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 97',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 97',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 97?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
  {
    id: 'ssb-srt-bulk-99',
    title: 'SRT & Self Description - Advanced Topic 99',
    readTimeMinutes: 12,
    content: [
      { type: 'heading', data: 'SRT & Self Description - Advanced Topic 99 Overview' },
      { type: 'text', data: 'This is the autogenerated study material for SRT & Self Description - Advanced Topic 99. The core concepts and detailed explanations for this topic will be available soon.' },
      { type: 'callout', data: '🚧 Content Under Development. Keep revising the key points!' },
      { type: 'list', data: [
        'Understand the basic principles of SRT & Self Description - Advanced Topic 99',
        'Review standard formulas and applications',
        'Practice related previous year questions'
      ]},
    ],
    keyPoints: [
      'Basic definition and scope of SRT & Self Description - Advanced Topic 99',
      'Important formulas and shortcuts',
      'Common question patterns in the exam'
    ],
    inlineQuiz: [
      { 
        question: 'What is the primary objective of studying SRT & Self Description - Advanced Topic 99?', 
        options: ['To memorize facts', 'To apply concepts to solve problems', 'To skip it in the exam', 'None of the above'], 
        correct: 1, 
        explanation: 'Applying concepts accurately is key to scoring well.' 
      }
    ]
  },
]
