// Total topics: 146
const ALL_TOPICS = [
  { id: 'afcat-gen-01-t01', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'History of Indian Air Force (formation, milestones, evolution)' },
  { id: 'afcat-gen-01-t02', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'IAF in Indo-Pak Wars (1947, 1965, 1971)' },
  { id: 'afcat-gen-01-t03', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'IAF in Kargil War (Operation Safed Sagar)' },
  { id: 'afcat-gen-01-t04', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'Major IAF Operations (Meghdoot, Poomalai, Cactus, Parakram, Balakot Airstrikes)' },
  { id: 'afcat-gen-01-t05', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'IAF Rank Structure (Airman to Air Chief Marshal)' },
  { id: 'afcat-gen-01-t06', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'IAF Commands (Western, Eastern, Central, Southern, South-Western, Training, Maintenance)' },
  { id: 'afcat-gen-01-t07', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'IAF Fighter Aircraft (Rafale, Su-30MKI, Tejas, MiG-29, Mirage 2000, Jaguar)' },
  { id: 'afcat-gen-01-t08', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'IAF Helicopters (Apache AH-64E, Chinook CH-47, Prachand, Mi-17, Dhruv, Chetak)' },
  { id: 'afcat-gen-01-t09', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'IAF Transport Aircraft (C-17 Globemaster, C-130J Super Hercules, Il-76, An-32, C-295)' },
  { id: 'afcat-gen-01-t10', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'IAF Trainer Aircraft (Hawk, Pilatus PC-7, HTT-40, Kiran)' },
  { id: 'afcat-gen-01-t11', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'IAF UAVs (Heron, Searcher, indigenous drones)' },
  { id: 'afcat-gen-01-t12', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'IAF AWACS & Special Mission Aircraft (A-50, Netra)' },
  { id: 'afcat-gen-01-t13', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'Indian Missiles — Surface-to-Air (Akash, S-400)' },
  { id: 'afcat-gen-01-t14', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'Indian Missiles — Air-to-Air (Astra, Python, Derby)' },
  { id: 'afcat-gen-01-t15', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'Indian Missiles — Ballistic (Agni series, Prithvi)' },
  { id: 'afcat-gen-01-t16', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'Indian Missiles — Cruise (BrahMos, Nirbhay)' },
  { id: 'afcat-gen-01-t17', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'Indian Missiles — Anti-Tank (Nag, HELINA)' },
  { id: 'afcat-gen-01-t18', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'IAF Bases & Stations (major locations)' },
  { id: 'afcat-gen-01-t19', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'Gallantry Awards — IAF specific (Vir Chakra, Kirti Chakra, Param Vir Chakra)' },
  { id: 'afcat-gen-01-t20', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-01', title: 'IAF Motto, Flag, Insignia, Air Force Day' },
  { id: 'afcat-gen-03-t01', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-03', title: 'Group Discussion (GD) — Topics on social issues, current affairs, defence' },
  { id: 'afcat-gen-03-t02', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-03', title: 'Group Planning Exercise (GPE) — Model-based tactical problem solving' },
  { id: 'afcat-gen-03-t03', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-03', title: 'Progressive Group Task (PGT) — Team obstacle crossing with resources' },
  { id: 'afcat-gen-03-t04', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-03', title: 'Half Group Task (HGT) — Smaller team obstacle task' },
  { id: 'afcat-gen-03-t05', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-03', title: 'Lecturette — 3-minute individual talk on chosen topic (4 options)' },
  { id: 'afcat-gen-03-t06', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-03', title: 'Snake Race / Group Obstacle Race' },
  { id: 'afcat-gen-03-t07', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-03', title: 'Individual Obstacles — 10 physical obstacles (rope, wall, ditch, etc.)' },
  { id: 'afcat-gen-03-t08', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-03', title: 'Command Task — Leading 2–3 members to complete an obstacle' },
  { id: 'afcat-gen-03-t09', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-03', title: 'Final Group Task (FGT) — Last team assessment obstacle' },
  { id: 'afcat-gen-04-t01', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-04', title: 'Personal Background & Family (upbringing, values, responsibilities)' },
  { id: 'afcat-gen-04-t02', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-04', title: 'Education & Academic Achievements' },
  { id: 'afcat-gen-04-t03', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-04', title: 'Hobbies & Extracurricular Activities (in-depth discussion)' },
  { id: 'afcat-gen-04-t04', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-04', title: 'Motivation for joining Indian Air Force' },
  { id: 'afcat-gen-04-t05', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-04', title: 'Knowledge of IAF — Current affairs, operations, aircraft' },
  { id: 'afcat-gen-04-t06', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-04', title: 'Situational & Behavioral Questions ("What would you do if...")' },
  { id: 'afcat-gen-04-t07', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-04', title: 'PIQ (Personal Information Questionnaire) — thorough preparation' },
  { id: 'afcat-gen-04-t08', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-04', title: 'Friends & Social Life discussion' },
  { id: 'afcat-gen-04-t09', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-04', title: 'Strengths, Weaknesses & Self-Awareness' },
  { id: 'afcat-gen-05-t01', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-05', title: 'Conference Procedure — Final board assessment, do\'s & don\'ts' },
  { id: 'afcat-gen-05-t02', exam: 'afcat', subject: 'General Awareness', chapter: 'afcat-gen-05', title: 'Officer Like Qualities (OLQs) — 15 qualities assessed throughout:' },
  { id: 'unknown-eng-01-t01', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Subject-Verb Agreement errors' },
  { id: 'unknown-eng-01-t02', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Tense consistency errors (Present/Past/Future)' },
  { id: 'unknown-eng-01-t03', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Article usage errors (a/an/the/zero article)' },
  { id: 'unknown-eng-01-t04', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Preposition errors (correct preposition with verbs, adjectives, nouns)' },
  { id: 'unknown-eng-01-t05', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Pronoun errors (reference, case, number agreement)' },
  { id: 'unknown-eng-01-t06', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Adjective vs. Adverb confusion' },
  { id: 'unknown-eng-01-t07', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Degree of comparison errors (comparative/superlative)' },
  { id: 'unknown-eng-01-t08', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Misplaced and dangling modifiers' },
  { id: 'unknown-eng-01-t09', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Parallelism / faulty parallel structure' },
  { id: 'unknown-eng-01-t10', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Redundancy and pleonasm errors' },
  { id: 'unknown-eng-01-t11', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Double negatives' },
  { id: 'unknown-eng-01-t12', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Incorrect use of conjunctions' },
  { id: 'unknown-eng-01-t13', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Errors in conditional sentences (if-clauses)' },
  { id: 'unknown-eng-01-t14', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Subject-complement agreement errors' },
  { id: 'unknown-eng-01-t15', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-01', title: 'Errors with non-finite verbs (gerunds, participles, infinitives)' },
  { id: 'unknown-eng-02-t01', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-02', title: 'Correcting grammatically incorrect segments' },
  { id: 'unknown-eng-02-t02', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-02', title: 'Improving sentence clarity and conciseness' },
  { id: 'unknown-eng-02-t03', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-02', title: 'Replacing wordy/awkward constructions' },
  { id: 'unknown-eng-03-t01', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-03', title: 'Grammar-based fill-ins (tense, article, preposition selection)' },
  { id: 'unknown-eng-03-t02', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-03', title: 'Vocabulary-based fill-ins (contextual word choice)' },
  { id: 'unknown-eng-03-t03', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-03', title: 'Phrasal verb fill-ins' },
  { id: 'unknown-eng-04-t01', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-04', title: 'Conversion rules across all tenses' },
  { id: 'unknown-eng-04-t02', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-04', title: 'Voice change with modals (can, may, should, must)' },
  { id: 'unknown-eng-04-t03', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-04', title: 'Imperative sentence voice conversion' },
  { id: 'unknown-eng-04-t04', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-04', title: 'Interrogative sentence voice conversion' },
  { id: 'unknown-eng-05-t01', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Reporting statements (declarative)' },
  { id: 'unknown-eng-05-t02', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Reporting questions (interrogative)' },
  { id: 'unknown-eng-05-t03', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Reporting commands/requests (imperative)' },
  { id: 'unknown-eng-05-t04', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Reporting exclamatory sentences' },
  { id: 'unknown-eng-05-t05', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Tense backshift rules and exceptions' },
  { id: 'unknown-eng-05-t06', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Properties of Triangles — Angle sum, exterior angle theorem, types of triangles' },
  { id: 'unknown-eng-05-t07', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Congruence of Triangles — SSS, SAS, ASA, AAS, RHS criteria' },
  { id: 'unknown-eng-05-t08', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Similar Triangles — AA, SAS, SSS similarity; Basic Proportionality Theorem (Thales)' },
  { id: 'unknown-eng-05-t09', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Concurrence — Medians (centroid), altitudes (orthocentre), angle bisectors (incentre), perpendicular bisectors (circumcentre)' },
  { id: 'unknown-eng-05-t10', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Pythagoras Theorem and its applications' },
  { id: 'unknown-eng-05-t11', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Quadrilaterals — Properties of parallelograms, rectangles, rhombus, squares, trapezium' },
  { id: 'unknown-eng-05-t12', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Circles — Properties (chord, arc, tangent, secant), angles in circles, tangent-radius relationship' },
  { id: 'unknown-eng-05-t13', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Loci — Concept of locus, standard loci problems' },
  { id: 'unknown-eng-05-t14', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Area of Triangles — Using base×height, Heron\'s formula' },
  { id: 'unknown-eng-05-t15', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Area of Quadrilaterals — Square, rectangle, parallelogram, rhombus, trapezium' },
  { id: 'unknown-eng-05-t16', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Area of Circles — Area, circumference, sector, segment' },
  { id: 'unknown-eng-05-t17', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Area of Composite/Irregular Figures (Field Book method)' },
  { id: 'unknown-eng-05-t18', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Surface Area and Volume of Cuboids and Cubes' },
  { id: 'unknown-eng-05-t19', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Surface Area and Volume of Right Circular Cylinders' },
  { id: 'unknown-eng-05-t20', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Surface Area and Volume of Right Circular Cones' },
  { id: 'unknown-eng-05-t21', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Surface Area and Volume of Spheres and Hemispheres' },
  { id: 'unknown-eng-05-t22', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Collection and Tabulation of Statistical Data — Frequency distribution' },
  { id: 'unknown-eng-05-t23', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Bar Graphs and Histograms — Construction and interpretation' },
  { id: 'unknown-eng-05-t24', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Pie Charts — Construction and interpretation' },
  { id: 'unknown-eng-05-t25', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Frequency Polygons and Ogives' },
  { id: 'unknown-eng-05-t26', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Mean — Arithmetic mean (direct, assumed mean, step deviation methods)' },
  { id: 'unknown-eng-05-t27', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Median — For grouped and ungrouped data' },
  { id: 'unknown-eng-05-t28', exam: 'unknown', subject: 'English', chapter: 'unknown-eng-05', title: 'Mode — For grouped and ungrouped data' },
  { id: 'unknown-mat-00-t01', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Concept of a set, representation (roster & set-builder)' },
  { id: 'unknown-mat-00-t02', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Types of sets (empty, finite, infinite, equal, subset, power set, universal)' },
  { id: 'unknown-mat-00-t03', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Operations on sets (union, intersection, difference, complement)' },
  { id: 'unknown-mat-00-t04', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Venn diagrams and their applications' },
  { id: 'unknown-mat-00-t05', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'De Morgan\'s laws' },
  { id: 'unknown-mat-00-t06', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Cartesian product of sets' },
  { id: 'unknown-mat-00-t07', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Relations — domain, range, co-domain' },
  { id: 'unknown-mat-00-t08', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Types of relations (reflexive, symmetric, transitive, equivalence)' },
  { id: 'unknown-mat-00-t09', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Functions — concept, domain, range, graph' },
  { id: 'unknown-mat-00-t10', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Types of functions (one-to-one, onto, bijective, inverse)' },
  { id: 'unknown-mat-00-t11', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Composite functions' },
  { id: 'unknown-mat-00-t12', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Real numbers — representation on a number line' },
  { id: 'unknown-mat-00-t13', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Complex numbers — basic properties (addition, subtraction, multiplication, division)' },
  { id: 'unknown-mat-00-t14', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Modulus and argument of a complex number' },
  { id: 'unknown-mat-00-t15', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Conjugate of a complex number' },
  { id: 'unknown-mat-00-t16', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Cube roots of unity' },
  { id: 'unknown-mat-00-t17', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Binary number system — conversion to/from decimal' },
  { id: 'unknown-mat-00-t18', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Quadratic equations with real coefficients' },
  { id: 'unknown-mat-00-t19', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Relation between roots and coefficients' },
  { id: 'unknown-mat-00-t20', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Nature of roots (discriminant)' },
  { id: 'unknown-mat-00-t21', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Formation of quadratic equations from given roots' },
  { id: 'unknown-mat-00-t22', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Linear inequations of two variables — graphical solution' },
  { id: 'unknown-mat-00-t23', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Fundamental principle of counting' },
  { id: 'unknown-mat-00-t24', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Permutations (nPr) — formulae and problems' },
  { id: 'unknown-mat-00-t25', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Combinations (nCr) — formulae and problems' },
  { id: 'unknown-mat-00-t26', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Applications and word problem' },
  { id: 'unknown-mat-00-t27', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Parliament — Lok Sabha, Rajya Sabha, legislative process' },
  { id: 'unknown-mat-00-t28', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'State Government — Governor, CM, State Legislature' },
  { id: 'unknown-mat-00-t29', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Judiciary — Supreme Court, High Courts, judicial review' },
  { id: 'unknown-mat-00-t30', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Emergency provisions (Articles 352, 356, 360)' },
  { id: 'unknown-mat-00-t31', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Election Commission of India' },
  { id: 'unknown-mat-00-t32', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Constitutional bodies — UPSC, CAG, Finance Commission' },
  { id: 'unknown-mat-00-t33', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'Panchayati Raj — 73rd and 74th Amendments' },
  { id: 'unknown-mat-00-t34', exam: 'unknown', subject: 'Mathematics', chapter: 'unknown-mat-00', title: 'National Integration — communalism, regionalism, linguism' },
  { id: 'unknown-eco-00-t35', exam: 'unknown', subject: 'ECONOMY', chapter: 'unknown-eco-00', title: 'Five-Year Plans — objectives, strategies, achievements' },
  { id: 'unknown-eco-00-t36', exam: 'unknown', subject: 'ECONOMY', chapter: 'unknown-eco-00', title: 'NITI Aayog (replacing Planning Commission)' },
  { id: 'unknown-eco-00-t37', exam: 'unknown', subject: 'ECONOMY', chapter: 'unknown-eco-00', title: 'Economic sectors — primary, secondary, tertiary' },
  { id: 'unknown-eco-00-t38', exam: 'unknown', subject: 'ECONOMY', chapter: 'unknown-eco-00', title: 'Cooperative movement and community development' },
  { id: 'unknown-eco-00-t39', exam: 'unknown', subject: 'ECONOMY', chapter: 'unknown-eco-00', title: 'Bhoodan, Sarvodaya, and land reform movements' },
  { id: 'unknown-eco-00-t40', exam: 'unknown', subject: 'ECONOMY', chapter: 'unknown-eco-00', title: 'Indian agriculture — problems, reforms, policies' },
  { id: 'unknown-eco-00-t41', exam: 'unknown', subject: 'ECONOMY', chapter: 'unknown-eco-00', title: 'Indian industry — public and private sector, liberalisation' },
  { id: 'unknown-cur-00-t42', exam: 'unknown', subject: 'CURRENT AFFAIRS & DEFENCE', chapter: 'unknown-cur-00', title: 'Important national events and developments' },
  { id: 'unknown-cur-00-t43', exam: 'unknown', subject: 'CURRENT AFFAIRS & DEFENCE', chapter: 'unknown-cur-00', title: 'Important international events and developments' },
  { id: 'unknown-cur-00-t44', exam: 'unknown', subject: 'CURRENT AFFAIRS & DEFENCE', chapter: 'unknown-cur-00', title: 'Prominent personalities — politics, sports, culture, science' },
  { id: 'unknown-cur-00-t45', exam: 'unknown', subject: 'CURRENT AFFAIRS & DEFENCE', chapter: 'unknown-cur-00', title: 'Cultural activities and sports — major events and winners' },
  { id: 'unknown-cur-00-t46', exam: 'unknown', subject: 'CURRENT AFFAIRS & DEFENCE', chapter: 'unknown-cur-00', title: 'India in international organizations — UN, NAM, BRICS, G20' },
  { id: 'unknown-cur-00-t47', exam: 'unknown', subject: 'CURRENT AFFAIRS & DEFENCE', chapter: 'unknown-cur-00', title: 'Democracy, socialism, communism — basic concepts' },
  { id: 'unknown-cur-00-t48', exam: 'unknown', subject: 'CURRENT AFFAIRS & DEFENCE', chapter: 'unknown-cur-00', title: 'India\'s role in the present world — foreign policy' },
  { id: 'unknown-cur-00-t49', exam: 'unknown', subject: 'CURRENT AFFAIRS & DEFENCE', chapter: 'unknown-cur-00', title: 'Defence awareness — Service Chiefs, ranks, commands' },
  { id: 'unknown-cur-00-t50', exam: 'unknown', subject: 'CURRENT AFFAIRS & DEFENCE', chapter: 'unknown-cur-00', title: 'Major joint military exercises' },
  { id: 'unknown-cur-00-t51', exam: 'unknown', subject: 'CURRENT AFFAIRS & DEFENCE', chapter: 'unknown-cur-00', title: 'Gallantry awards — Param Vir Chakra, Maha Vir Chakra, Vir Chakra' },
  { id: 'unknown-cur-00-t52', exam: 'unknown', subject: 'CURRENT AFFAIRS & DEFENCE', chapter: 'unknown-cur-00', title: 'New defence equipment and indigenization programs (Make in India defence)' },
  { id: 'unknown-cur-00-t53', exam: 'unknown', subject: 'CURRENT AFFAIRS & DEFENCE', chapter: 'unknown-cur-00', title: 'Important government schemes and policies' },
];
module.exports = ALL_TOPICS;
