import { TopicContent } from './types'
import { AUTOGEN_REGISTRY } from './autogen'

// You can import custom manual topics here and override them in the CONTENT_REGISTRY
// import { CUSTOM_NDA_CALC } from './nda/custom-nda-calc'

export const CONTENT_REGISTRY: Record<string, TopicContent[]> = {
  ...AUTOGEN_REGISTRY,
  // 'nda-calc': CUSTOM_NDA_CALC, // This would override the autogenerated template
}

export function getTopicsForChapter(chapterId: string): TopicContent[] {
  return CONTENT_REGISTRY[chapterId] ?? []
}

export function getTopic(chapterId: string, topicId: string): TopicContent | null {
  return CONTENT_REGISTRY[chapterId]?.find(t => t.id === topicId) ?? null
}
